# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.get_audit_logs_response import GetAuditLogsResponse

class TestGetAuditLogsResponse(unittest.TestCase):
    """GetAuditLogsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAuditLogsResponse:
        """Test GetAuditLogsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAuditLogsResponse`
        """
        model = GetAuditLogsResponse()
        if include_optional:
            return GetAuditLogsResponse(
                status = 'success',
                audit_logs = [
                    client.models.pick_tenant_audit_log/tenant_audit_log_keys_.Pick_TenantAuditLog.TenantAuditLogKeys_(
                        _id = '', 
                        url = '', 
                        user_id = '', 
                        username = '', 
                        resource_name = '', 
                        crud_type = 'c', 
                        from = 'ui', 
                        ip = '', 
                        when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        server_start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        object_details = {
                            'key' : null
                            }, )
                    ]
            )
        else:
            return GetAuditLogsResponse(
                status = 'success',
                audit_logs = [
                    client.models.pick_tenant_audit_log/tenant_audit_log_keys_.Pick_TenantAuditLog.TenantAuditLogKeys_(
                        _id = '', 
                        url = '', 
                        user_id = '', 
                        username = '', 
                        resource_name = '', 
                        crud_type = 'c', 
                        from = 'ui', 
                        ip = '', 
                        when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        server_start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        object_details = {
                            'key' : null
                            }, )
                    ],
        )
        """

    def testGetAuditLogsResponse(self):
        """Test GetAuditLogsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
