# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.user_notification_write_response import UserNotificationWriteResponse

class TestUserNotificationWriteResponse(unittest.TestCase):
    """UserNotificationWriteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserNotificationWriteResponse:
        """Test UserNotificationWriteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserNotificationWriteResponse`
        """
        model = UserNotificationWriteResponse()
        if include_optional:
            return UserNotificationWriteResponse(
                status = 'success',
                matched_count = 56,
                modified_count = 56
            )
        else:
            return UserNotificationWriteResponse(
                status = 'success',
                matched_count = 56,
                modified_count = 56,
        )
        """

    def testUserNotificationWriteResponse(self):
        """Test UserNotificationWriteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
