# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.update_question_config_body import UpdateQuestionConfigBody

class TestUpdateQuestionConfigBody(unittest.TestCase):
    """UpdateQuestionConfigBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateQuestionConfigBody:
        """Test UpdateQuestionConfigBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateQuestionConfigBody`
        """
        model = UpdateQuestionConfigBody()
        if include_optional:
            return UpdateQuestionConfigBody(
                name = '',
                question = '',
                help_text = '',
                type = '',
                num_stars = 1.337,
                min = 1.337,
                max = 1.337,
                default_value = 1.337,
                label_negative = '',
                label_positive = '',
                custom_options = [
                    client.models.question_config_custom_options_inner.QuestionConfig_customOptions_inner(
                        image_src = '', 
                        name = '', )
                    ],
                sub_question_ids = [
                    ''
                    ],
                always_show_sub_questions = True,
                reporting_order = 1.337
            )
        else:
            return UpdateQuestionConfigBody(
        )
        """

    def testUpdateQuestionConfigBody(self):
        """Test UpdateQuestionConfigBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
