# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.get_my_notifications_response import GetMyNotificationsResponse

class TestGetMyNotificationsResponse(unittest.TestCase):
    """GetMyNotificationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMyNotificationsResponse:
        """Test GetMyNotificationsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMyNotificationsResponse`
        """
        model = GetMyNotificationsResponse()
        if include_optional:
            return GetMyNotificationsResponse(
                translations = {
                    'key' : ''
                    },
                is_subscribed = True,
                has_more = True,
                notifications = [
                    generated.models.renderable_user_notification.RenderableUserNotification(
                        conversation_id = '', 
                        context_html = '', 
                        from_user_names = [
                            ''
                            ], 
                        from_user_ids = [
                            ''
                            ], 
                        related_ids = [
                            ''
                            ], 
                        count = 56, 
                        opted_out = True, 
                        from_user_avatar_src = '', 
                        from_user_id = '', 
                        from_user_name = '', 
                        from_comment_id = '', 
                        type = 0, 
                        created_at = '', 
                        sent = '', 
                        viewed = '', 
                        related_object_id = '', 
                        related_object_type = 0, 
                        page_title = '', 
                        url = '', 
                        url_id = '', 
                        _id = '', )
                    ],
                status = 'success'
            )
        else:
            return GetMyNotificationsResponse(
                is_subscribed = True,
                has_more = True,
                notifications = [
                    generated.models.renderable_user_notification.RenderableUserNotification(
                        conversation_id = '', 
                        context_html = '', 
                        from_user_names = [
                            ''
                            ], 
                        from_user_ids = [
                            ''
                            ], 
                        related_ids = [
                            ''
                            ], 
                        count = 56, 
                        opted_out = True, 
                        from_user_avatar_src = '', 
                        from_user_id = '', 
                        from_user_name = '', 
                        from_comment_id = '', 
                        type = 0, 
                        created_at = '', 
                        sent = '', 
                        viewed = '', 
                        related_object_id = '', 
                        related_object_type = 0, 
                        page_title = '', 
                        url = '', 
                        url_id = '', 
                        _id = '', )
                    ],
                status = 'success',
        )
        """

    def testGetMyNotificationsResponse(self):
        """Test GetMyNotificationsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
