# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vote_style import VoteStyle

class TestVoteStyle(unittest.TestCase):
    """VoteStyle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVoteStyle(self):
        """Test VoteStyle"""
        # inst = VoteStyle()

if __name__ == '__main__':
    unittest.main()
