# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.get_hash_tags_response import GetHashTagsResponse

class TestGetHashTagsResponse(unittest.TestCase):
    """GetHashTagsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHashTagsResponse:
        """Test GetHashTagsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHashTagsResponse`
        """
        model = GetHashTagsResponse()
        if include_optional:
            return GetHashTagsResponse(
                status = 'success',
                hash_tags = [
                    client.models.tenant_hash_tag.TenantHashTag(
                        _id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tenant_id = '', 
                        tag = '', 
                        url = '', )
                    ]
            )
        else:
            return GetHashTagsResponse(
                status = 'success',
                hash_tags = [
                    client.models.tenant_hash_tag.TenantHashTag(
                        _id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tenant_id = '', 
                        tag = '', 
                        url = '', )
                    ],
        )
        """

    def testGetHashTagsResponse(self):
        """Test GetHashTagsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
