# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.api.public_api import PublicApi


class TestPublicApi(unittest.TestCase):
    """PublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicApi()

    def tearDown(self) -> None:
        pass

    def test_block_from_comment_public(self) -> None:
        """Test case for block_from_comment_public

        """
        pass

    def test_checked_comments_for_blocked(self) -> None:
        """Test case for checked_comments_for_blocked

        """
        pass

    def test_create_comment_public(self) -> None:
        """Test case for create_comment_public

        """
        pass

    def test_create_feed_post_public(self) -> None:
        """Test case for create_feed_post_public

        """
        pass

    def test_create_v1_page_react(self) -> None:
        """Test case for create_v1_page_react

        """
        pass

    def test_create_v2_page_react(self) -> None:
        """Test case for create_v2_page_react

        """
        pass

    def test_delete_comment_public(self) -> None:
        """Test case for delete_comment_public

        """
        pass

    def test_delete_comment_vote(self) -> None:
        """Test case for delete_comment_vote

        """
        pass

    def test_delete_feed_post_public(self) -> None:
        """Test case for delete_feed_post_public

        """
        pass

    def test_delete_v1_page_react(self) -> None:
        """Test case for delete_v1_page_react

        """
        pass

    def test_delete_v2_page_react(self) -> None:
        """Test case for delete_v2_page_react

        """
        pass

    def test_flag_comment_public(self) -> None:
        """Test case for flag_comment_public

        """
        pass

    def test_get_comment_text(self) -> None:
        """Test case for get_comment_text

        """
        pass

    def test_get_comment_vote_user_names(self) -> None:
        """Test case for get_comment_vote_user_names

        """
        pass

    def test_get_comments_for_user(self) -> None:
        """Test case for get_comments_for_user

        """
        pass

    def test_get_comments_public(self) -> None:
        """Test case for get_comments_public

        """
        pass

    def test_get_event_log(self) -> None:
        """Test case for get_event_log

        """
        pass

    def test_get_feed_posts_public(self) -> None:
        """Test case for get_feed_posts_public

        """
        pass

    def test_get_feed_posts_stats(self) -> None:
        """Test case for get_feed_posts_stats

        """
        pass

    def test_get_gif_large(self) -> None:
        """Test case for get_gif_large

        """
        pass

    def test_get_gifs_search(self) -> None:
        """Test case for get_gifs_search

        """
        pass

    def test_get_gifs_trending(self) -> None:
        """Test case for get_gifs_trending

        """
        pass

    def test_get_global_event_log(self) -> None:
        """Test case for get_global_event_log

        """
        pass

    def test_get_offline_users(self) -> None:
        """Test case for get_offline_users

        """
        pass

    def test_get_online_users(self) -> None:
        """Test case for get_online_users

        """
        pass

    def test_get_pages_public(self) -> None:
        """Test case for get_pages_public

        """
        pass

    def test_get_translations(self) -> None:
        """Test case for get_translations

        """
        pass

    def test_get_user_notification_count(self) -> None:
        """Test case for get_user_notification_count

        """
        pass

    def test_get_user_notifications(self) -> None:
        """Test case for get_user_notifications

        """
        pass

    def test_get_user_presence_statuses(self) -> None:
        """Test case for get_user_presence_statuses

        """
        pass

    def test_get_user_reacts_public(self) -> None:
        """Test case for get_user_reacts_public

        """
        pass

    def test_get_users_info(self) -> None:
        """Test case for get_users_info

        """
        pass

    def test_get_v1_page_likes(self) -> None:
        """Test case for get_v1_page_likes

        """
        pass

    def test_get_v2_page_react_users(self) -> None:
        """Test case for get_v2_page_react_users

        """
        pass

    def test_get_v2_page_reacts(self) -> None:
        """Test case for get_v2_page_reacts

        """
        pass

    def test_lock_comment(self) -> None:
        """Test case for lock_comment

        """
        pass

    def test_logout_public(self) -> None:
        """Test case for logout_public

        """
        pass

    def test_pin_comment(self) -> None:
        """Test case for pin_comment

        """
        pass

    def test_react_feed_post_public(self) -> None:
        """Test case for react_feed_post_public

        """
        pass

    def test_reset_user_notification_count(self) -> None:
        """Test case for reset_user_notification_count

        """
        pass

    def test_reset_user_notifications(self) -> None:
        """Test case for reset_user_notifications

        """
        pass

    def test_search_users(self) -> None:
        """Test case for search_users

        """
        pass

    def test_set_comment_text(self) -> None:
        """Test case for set_comment_text

        """
        pass

    def test_un_block_comment_public(self) -> None:
        """Test case for un_block_comment_public

        """
        pass

    def test_un_lock_comment(self) -> None:
        """Test case for un_lock_comment

        """
        pass

    def test_un_pin_comment(self) -> None:
        """Test case for un_pin_comment

        """
        pass

    def test_update_feed_post_public(self) -> None:
        """Test case for update_feed_post_public

        """
        pass

    def test_update_user_notification_comment_subscription_status(self) -> None:
        """Test case for update_user_notification_comment_subscription_status

        """
        pass

    def test_update_user_notification_page_subscription_status(self) -> None:
        """Test case for update_user_notification_page_subscription_status

        """
        pass

    def test_update_user_notification_status(self) -> None:
        """Test case for update_user_notification_status

        """
        pass

    def test_upload_image(self) -> None:
        """Test case for upload_image

        """
        pass

    def test_vote_comment(self) -> None:
        """Test case for vote_comment

        """
        pass


if __name__ == '__main__':
    unittest.main()
