# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.aggregation_request_sort import AggregationRequestSort

class TestAggregationRequestSort(unittest.TestCase):
    """AggregationRequestSort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AggregationRequestSort:
        """Test AggregationRequestSort
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AggregationRequestSort`
        """
        model = AggregationRequestSort()
        if include_optional:
            return AggregationRequestSort(
                dir = 'asc',
                var_field = ''
            )
        else:
            return AggregationRequestSort(
                dir = 'asc',
                var_field = '',
        )
        """

    def testAggregationRequestSort(self):
        """Test AggregationRequestSort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
