# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.get_comments_response_with_presence_public_comment import GetCommentsResponseWithPresencePublicComment

class TestGetCommentsResponseWithPresencePublicComment(unittest.TestCase):
    """GetCommentsResponseWithPresencePublicComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCommentsResponseWithPresencePublicComment:
        """Test GetCommentsResponseWithPresencePublicComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCommentsResponseWithPresencePublicComment`
        """
        model = GetCommentsResponseWithPresencePublicComment()
        if include_optional:
            return GetCommentsResponseWithPresencePublicComment(
                status_code = 56,
                status = '',
                code = '',
                reason = '',
                translated_warning = '',
                comments = [
                    null
                    ],
                user = generated.models.user_session_info.UserSessionInfo(
                    id = '', 
                    authorized = True, 
                    avatar_src = '', 
                    badges = [
                        generated.models.comment_user_badge_info.CommentUserBadgeInfo(
                            id = '', 
                            type = 56, 
                            description = '', 
                            display_label = '', 
                            display_src = '', 
                            background_color = '', 
                            border_color = '', 
                            text_color = '', 
                            css_class = '', )
                        ], 
                    display_label = '', 
                    display_name = '', 
                    email = '', 
                    group_ids = [
                        ''
                        ], 
                    has_blocked_users = True, 
                    is_anon_session = True, 
                    session_id = '', 
                    username = '', 
                    website_url = '', ),
                url_id_clean = '',
                last_gen_date = 56,
                includes_past_pages = True,
                is_demo = True,
                comment_count = 56,
                is_site_admin = True,
                has_billing_issue = True,
                module_data = {
                    'key' : None
                    },
                page_number = 56,
                is_white_labeled = True,
                is_prod = True,
                is_crawler = True,
                notification_count = 56,
                has_more = True,
                is_closed = True,
                presence_poll_state = 56,
                custom_config = generated.models.custom_config_parameters.CustomConfigParameters(
                    absolute_and_relative_dates = True, 
                    absolute_dates = True, 
                    allow_anon = True, 
                    allow_anon_flag = True, 
                    allow_anon_votes = True, 
                    allowed_languages = [
                        ''
                        ], 
                    collapse_replies = True, 
                    comment_count_format = '', 
                    comment_html_rendering_mode = 0, 
                    comment_thread_delete_mode = null, 
                    commenter_name_format = null, 
                    count_above_toggle = 56, 
                    custom_css = '', 
                    default_avatar_src = '', 
                    default_sort_direction = null, 
                    default_username = '', 
                    disable_auto_admin_migration = True, 
                    disable_auto_hash_tag_creation = True, 
                    disable_blocking = True, 
                    disable_commenter_comment_delete = True, 
                    disable_commenter_comment_edit = True, 
                    disable_email_inputs = True, 
                    disable_live_commenting = True, 
                    disable_notification_bell = True, 
                    disable_profiles = True, 
                    disable_success_message = True, 
                    disable_toolbar = True, 
                    disable_unverified_label = True, 
                    disable_voting = True, 
                    enable_commenter_links = True, 
                    enable_search = True, 
                    enable_spoilers = True, 
                    enable_third_party_cookie_bypass = True, 
                    enable_view_counts = True, 
                    enable_vote_list = True, 
                    enable_wysiwyg = True, 
                    gif_rating = 'g', 
                    has_dark_background = True, 
                    header_html = '', 
                    hide_avatars = True, 
                    hide_comments_under_count_text_format = '', 
                    image_content_profanity_level = 'off', 
                    input_after_comments = True, 
                    limit_comments_by_groups = True, 
                    locale = '', 
                    max_comment_character_length = 56, 
                    max_comment_created_count_pupm = 56, 
                    no_custom_config = True, 
                    no_image_uploads = True, 
                    no_styles = True, 
                    page_size = 56, 
                    readonly = True, 
                    require_sso = True, 
                    enable_resize_handle = True, 
                    restricted_link_domains = [
                        ''
                        ], 
                    show_badges_in_top_bar = True, 
                    show_comment_save_success = True, 
                    show_live_right_away = True, 
                    show_question = True, 
                    spam_rules = [
                        generated.models.spam_rule.SpamRule(
                            actions = [
                                'spam'
                                ], 
                            comment_contains = '', )
                        ], 
                    sso_sec_lvl = 0, 
                    translations = null, 
                    use_show_comments_toggle = True, 
                    use_single_line_comment_input = True, 
                    vote_style = 0, 
                    widget_question_id = '', 
                    widget_question_results_style = 0, 
                    widget_question_style = 0, 
                    widget_question_when_to_save = 0, 
                    widget_questions_required = 0, 
                    widget_sub_question_visibility = 0, 
                    wrap = True, ),
                url_id_ws = '',
                user_id_ws = '',
                tenant_id_ws = ''
            )
        else:
            return GetCommentsResponseWithPresencePublicComment(
                status = '',
                comments = [
                    null
                    ],
                user = generated.models.user_session_info.UserSessionInfo(
                    id = '', 
                    authorized = True, 
                    avatar_src = '', 
                    badges = [
                        generated.models.comment_user_badge_info.CommentUserBadgeInfo(
                            id = '', 
                            type = 56, 
                            description = '', 
                            display_label = '', 
                            display_src = '', 
                            background_color = '', 
                            border_color = '', 
                            text_color = '', 
                            css_class = '', )
                        ], 
                    display_label = '', 
                    display_name = '', 
                    email = '', 
                    group_ids = [
                        ''
                        ], 
                    has_blocked_users = True, 
                    is_anon_session = True, 
                    session_id = '', 
                    username = '', 
                    website_url = '', ),
                page_number = 56,
        )
        """

    def testGetCommentsResponseWithPresencePublicComment(self):
        """Test GetCommentsResponseWithPresencePublicComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
