# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.get_domain_configs_response import GetDomainConfigsResponse

class TestGetDomainConfigsResponse(unittest.TestCase):
    """GetDomainConfigsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDomainConfigsResponse:
        """Test GetDomainConfigsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDomainConfigsResponse`
        """
        model = GetDomainConfigsResponse()
        if include_optional:
            return GetDomainConfigsResponse(
                configurations = client.models.configurations.configurations(),
                status = client.models.status.status(),
                reason = '',
                code = ''
            )
        else:
            return GetDomainConfigsResponse(
                status = client.models.status.status(),
        )
        """

    def testGetDomainConfigsResponse(self):
        """Test GetDomainConfigsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
