# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.api_audit_log import APIAuditLog

class TestAPIAuditLog(unittest.TestCase):
    """APIAuditLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIAuditLog:
        """Test APIAuditLog
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIAuditLog`
        """
        model = APIAuditLog()
        if include_optional:
            return APIAuditLog(
                id = '',
                user_id = '',
                username = '',
                resource_name = '',
                crud_type = 'c',
                var_from = 'ui',
                url = '',
                ip = '',
                when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                server_start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                object_details = {
                    'key' : null
                    }
            )
        else:
            return APIAuditLog(
                id = '',
                resource_name = '',
                crud_type = 'c',
        )
        """

    def testAPIAuditLog(self):
        """Test APIAuditLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
