# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.api_page import APIPage

class TestAPIPage(unittest.TestCase):
    """APIPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIPage:
        """Test APIPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIPage`
        """
        model = APIPage()
        if include_optional:
            return APIPage(
                is_closed = True,
                accessible_by_group_ids = [
                    ''
                    ],
                root_comment_count = 56,
                comment_count = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                url = '',
                url_id = '',
                id = ''
            )
        else:
            return APIPage(
                root_comment_count = 56,
                comment_count = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                url_id = '',
                id = '',
        )
        """

    def testAPIPage(self):
        """Test APIPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
