# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.comment_questions_required import CommentQuestionsRequired

class TestCommentQuestionsRequired(unittest.TestCase):
    """CommentQuestionsRequired unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommentQuestionsRequired(self):
        """Test CommentQuestionsRequired"""
        # inst = CommentQuestionsRequired()

if __name__ == '__main__':
    unittest.main()
