# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.get_cached_notification_count_response import GetCachedNotificationCountResponse

class TestGetCachedNotificationCountResponse(unittest.TestCase):
    """GetCachedNotificationCountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCachedNotificationCountResponse:
        """Test GetCachedNotificationCountResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCachedNotificationCountResponse`
        """
        model = GetCachedNotificationCountResponse()
        if include_optional:
            return GetCachedNotificationCountResponse(
                status = 'success',
                data = client.models.user_notification_count.UserNotificationCount(
                    _id = '', 
                    count = 1.337, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GetCachedNotificationCountResponse(
                status = 'success',
                data = client.models.user_notification_count.UserNotificationCount(
                    _id = '', 
                    count = 1.337, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testGetCachedNotificationCountResponse(self):
        """Test GetCachedNotificationCountResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
