# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.create_v1_page_react import CreateV1PageReact

class TestCreateV1PageReact(unittest.TestCase):
    """CreateV1PageReact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateV1PageReact:
        """Test CreateV1PageReact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateV1PageReact`
        """
        model = CreateV1PageReact()
        if include_optional:
            return CreateV1PageReact(
                code = '',
                status = 'success'
            )
        else:
            return CreateV1PageReact(
                status = 'success',
        )
        """

    def testCreateV1PageReact(self):
        """Test CreateV1PageReact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
