# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.api_banned_user_with_multi_match_info import APIBannedUserWithMultiMatchInfo

class TestAPIBannedUserWithMultiMatchInfo(unittest.TestCase):
    """APIBannedUserWithMultiMatchInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIBannedUserWithMultiMatchInfo:
        """Test APIBannedUserWithMultiMatchInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIBannedUserWithMultiMatchInfo`
        """
        model = APIBannedUserWithMultiMatchInfo()
        if include_optional:
            return APIBannedUserWithMultiMatchInfo(
                id = '',
                user_id = '',
                ban_type = '',
                email = '',
                ip_hash = '',
                banned_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                has_email_wildcard = True,
                ban_reason = '',
                matches = [
                    client.models.banned_user_match.BannedUserMatch(
                        matched_on = 'userId', 
                        matched_on_value = null, )
                    ]
            )
        else:
            return APIBannedUserWithMultiMatchInfo(
                id = '',
                ban_type = '',
                banned_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                has_email_wildcard = True,
                matches = [
                    client.models.banned_user_match.BannedUserMatch(
                        matched_on = 'userId', 
                        matched_on_value = null, )
                    ],
        )
        """

    def testAPIBannedUserWithMultiMatchInfo(self):
        """Test APIBannedUserWithMultiMatchInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
