# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.get_domain_configs200_response_any_of import GetDomainConfigs200ResponseAnyOf

class TestGetDomainConfigs200ResponseAnyOf(unittest.TestCase):
    """GetDomainConfigs200ResponseAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDomainConfigs200ResponseAnyOf:
        """Test GetDomainConfigs200ResponseAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDomainConfigs200ResponseAnyOf`
        """
        model = GetDomainConfigs200ResponseAnyOf()
        if include_optional:
            return GetDomainConfigs200ResponseAnyOf(
                configurations = None,
                status = None
            )
        else:
            return GetDomainConfigs200ResponseAnyOf(
                configurations = None,
                status = None,
        )
        """

    def testGetDomainConfigs200ResponseAnyOf(self):
        """Test GetDomainConfigs200ResponseAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
