# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.api_comment_base import APICommentBase

class TestAPICommentBase(unittest.TestCase):
    """APICommentBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APICommentBase:
        """Test APICommentBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APICommentBase`
        """
        model = APICommentBase()
        if include_optional:
            return APICommentBase(
                id = '',
                ai_determined_spam = True,
                anon_user_id = '',
                approved = True,
                avatar_src = '',
                badges = [
                    client.models.comment_user_badge_info.CommentUserBadgeInfo(
                        id = '', 
                        type = 56, 
                        description = '', 
                        display_label = '', 
                        display_src = '', 
                        background_color = '', 
                        border_color = '', 
                        text_color = '', 
                        css_class = '', )
                    ],
                comment = '',
                comment_html = '',
                commenter_email = '',
                commenter_link = '',
                commenter_name = '',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                display_label = '',
                domain = '',
                external_id = '',
                external_parent_id = '',
                expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                feedback_ids = [
                    ''
                    ],
                flag_count = 56,
                from_product_id = 56,
                has_code = True,
                has_images = True,
                has_links = True,
                hash_tags = [
                    client.models.comment_user_hash_tag_info.CommentUserHashTagInfo(
                        id = '', 
                        tag = '', 
                        url = '', 
                        retain = True, )
                    ],
                is_by_admin = True,
                is_by_moderator = True,
                is_deleted = True,
                is_deleted_user = True,
                is_pinned = True,
                is_locked = True,
                is_spam = True,
                local_date_hours = 56,
                local_date_string = '',
                locale = '',
                mentions = [
                    client.models.comment_user_mention_info.CommentUserMentionInfo(
                        id = '', 
                        tag = '', 
                        raw_tag = '', 
                        type = 'user', 
                        sent = True, )
                    ],
                meta = {
                    'key' : null
                    },
                moderation_group_ids = [
                    ''
                    ],
                notification_sent_for_parent = True,
                notification_sent_for_parent_tenant = True,
                page_title = '',
                parent_id = '',
                rating = 1.337,
                reviewed = True,
                tenant_id = '',
                url = '',
                url_id = '',
                url_id_raw = '',
                user_id = '',
                verified = True,
                verified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                votes = 56,
                votes_down = 56,
                votes_up = 56
            )
        else:
            return APICommentBase(
                id = '',
                approved = True,
                comment = '',
                comment_html = '',
                commenter_name = '',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                locale = '',
                tenant_id = '',
                url = '',
                url_id = '',
                verified = True,
        )
        """

    def testAPICommentBase(self):
        """Test APICommentBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
