# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.pages_sort_by import PagesSortBy

class TestPagesSortBy(unittest.TestCase):
    """PagesSortBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagesSortBy(self):
        """Test PagesSortBy"""
        # inst = PagesSortBy()

if __name__ == '__main__':
    unittest.main()
