# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.feed_post_media_item import FeedPostMediaItem

class TestFeedPostMediaItem(unittest.TestCase):
    """FeedPostMediaItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeedPostMediaItem:
        """Test FeedPostMediaItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeedPostMediaItem`
        """
        model = FeedPostMediaItem()
        if include_optional:
            return FeedPostMediaItem(
                title = '',
                link_url = '',
                sizes = [
                    client.models.feed_post_media_item_asset.FeedPostMediaItemAsset(
                        w = 56, 
                        h = 56, 
                        src = '', )
                    ]
            )
        else:
            return FeedPostMediaItem(
                sizes = [
                    client.models.feed_post_media_item_asset.FeedPostMediaItemAsset(
                        w = 56, 
                        h = 56, 
                        src = '', )
                    ],
        )
        """

    def testFeedPostMediaItem(self):
        """Test FeedPostMediaItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
