# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.feed_post import FeedPost

class TestFeedPost(unittest.TestCase):
    """FeedPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeedPost:
        """Test FeedPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeedPost`
        """
        model = FeedPost()
        if include_optional:
            return FeedPost(
                id = '',
                tenant_id = '',
                title = '',
                from_user_id = '',
                from_user_display_name = '',
                from_user_avatar = '',
                from_ip_hash = '',
                tags = [
                    ''
                    ],
                weight = 1.337,
                meta = {
                    'key' : ''
                    },
                content_html = '',
                media = [
                    generated.models.feed_post_media_item.FeedPostMediaItem(
                        title = '', 
                        link_url = '', 
                        sizes = [
                            generated.models.feed_post_media_item_asset.FeedPostMediaItemAsset(
                                w = 56, 
                                h = 56, 
                                src = '', )
                            ], )
                    ],
                links = [
                    generated.models.feed_post_link.FeedPostLink(
                        text = '', 
                        title = '', 
                        description = '', 
                        url = '', )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                reacts = {
                    'key' : 56
                    },
                comment_count = 56
            )
        else:
            return FeedPost(
                id = '',
                tenant_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testFeedPost(self):
        """Test FeedPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
