# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.api_status import APIStatus

class TestAPIStatus(unittest.TestCase):
    """APIStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPIStatus(self):
        """Test APIStatus"""
        # inst = APIStatus()

if __name__ == '__main__':
    unittest.main()
