# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.get_tenant_package_response import GetTenantPackageResponse

class TestGetTenantPackageResponse(unittest.TestCase):
    """GetTenantPackageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTenantPackageResponse:
        """Test GetTenantPackageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTenantPackageResponse`
        """
        model = GetTenantPackageResponse()
        if include_optional:
            return GetTenantPackageResponse(
                status = 'success',
                tenant_package = client.models.tenant_package.TenantPackage(
                    _id = '', 
                    name = '', 
                    tenant_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    monthly_cost_usd = 1.337, 
                    yearly_cost_usd = 1.337, 
                    monthly_stripe_plan_id = '', 
                    yearly_stripe_plan_id = '', 
                    max_monthly_page_loads = 1.337, 
                    max_monthly_api_credits = 1.337, 
                    max_monthly_small_widgets_credits = 1.337, 
                    max_monthly_comments = 1.337, 
                    max_concurrent_users = 1.337, 
                    max_tenant_users = 1.337, 
                    max_sso_users = 1.337, 
                    max_moderators = 1.337, 
                    max_domains = 1.337, 
                    max_white_labeled_tenants = 1.337, 
                    max_monthly_event_log_requests = 1.337, 
                    has_white_labeling = True, 
                    has_debranding = True, 
                    has_llm_spam_detection = True, 
                    for_who_text = '', 
                    feature_taglines = [
                        ''
                        ], 
                    has_auditing = True, 
                    has_flex_pricing = True, 
                    enable_saml = True, 
                    flex_page_load_cost_cents = 1.337, 
                    flex_page_load_unit = 1.337, 
                    flex_comment_cost_cents = 1.337, 
                    flex_comment_unit = 1.337, 
                    flex_sso_user_cost_cents = 1.337, 
                    flex_sso_user_unit = 1.337, 
                    flex_api_credit_cost_cents = 1.337, 
                    flex_api_credit_unit = 1.337, 
                    flex_small_widgets_credit_cost_cents = 1.337, 
                    flex_small_widgets_credit_unit = 1.337, 
                    flex_moderator_cost_cents = 1.337, 
                    flex_moderator_unit = 1.337, 
                    flex_admin_cost_cents = 1.337, 
                    flex_admin_unit = 1.337, 
                    flex_domain_cost_cents = 1.337, 
                    flex_domain_unit = 1.337, 
                    flex_chat_gpt_cost_cents = 1.337, 
                    flex_chat_gpt_unit = 1.337, 
                    flex_minimum_cost_cents = 1.337, 
                    flex_managed_tenant_cost_cents = 1.337, 
                    flex_sso_admin_cost_cents = 1.337, 
                    flex_sso_admin_unit = 1.337, 
                    flex_sso_moderator_cost_cents = 1.337, 
                    flex_sso_moderator_unit = 1.337, 
                    is_sso_billing_monthly_active_users = True, )
            )
        else:
            return GetTenantPackageResponse(
                status = 'success',
                tenant_package = client.models.tenant_package.TenantPackage(
                    _id = '', 
                    name = '', 
                    tenant_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    monthly_cost_usd = 1.337, 
                    yearly_cost_usd = 1.337, 
                    monthly_stripe_plan_id = '', 
                    yearly_stripe_plan_id = '', 
                    max_monthly_page_loads = 1.337, 
                    max_monthly_api_credits = 1.337, 
                    max_monthly_small_widgets_credits = 1.337, 
                    max_monthly_comments = 1.337, 
                    max_concurrent_users = 1.337, 
                    max_tenant_users = 1.337, 
                    max_sso_users = 1.337, 
                    max_moderators = 1.337, 
                    max_domains = 1.337, 
                    max_white_labeled_tenants = 1.337, 
                    max_monthly_event_log_requests = 1.337, 
                    has_white_labeling = True, 
                    has_debranding = True, 
                    has_llm_spam_detection = True, 
                    for_who_text = '', 
                    feature_taglines = [
                        ''
                        ], 
                    has_auditing = True, 
                    has_flex_pricing = True, 
                    enable_saml = True, 
                    flex_page_load_cost_cents = 1.337, 
                    flex_page_load_unit = 1.337, 
                    flex_comment_cost_cents = 1.337, 
                    flex_comment_unit = 1.337, 
                    flex_sso_user_cost_cents = 1.337, 
                    flex_sso_user_unit = 1.337, 
                    flex_api_credit_cost_cents = 1.337, 
                    flex_api_credit_unit = 1.337, 
                    flex_small_widgets_credit_cost_cents = 1.337, 
                    flex_small_widgets_credit_unit = 1.337, 
                    flex_moderator_cost_cents = 1.337, 
                    flex_moderator_unit = 1.337, 
                    flex_admin_cost_cents = 1.337, 
                    flex_admin_unit = 1.337, 
                    flex_domain_cost_cents = 1.337, 
                    flex_domain_unit = 1.337, 
                    flex_chat_gpt_cost_cents = 1.337, 
                    flex_chat_gpt_unit = 1.337, 
                    flex_minimum_cost_cents = 1.337, 
                    flex_managed_tenant_cost_cents = 1.337, 
                    flex_sso_admin_cost_cents = 1.337, 
                    flex_sso_admin_unit = 1.337, 
                    flex_sso_moderator_cost_cents = 1.337, 
                    flex_sso_moderator_unit = 1.337, 
                    is_sso_billing_monthly_active_users = True, ),
        )
        """

    def testGetTenantPackageResponse(self):
        """Test GetTenantPackageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
