# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.email_template_definition import EmailTemplateDefinition

class TestEmailTemplateDefinition(unittest.TestCase):
    """EmailTemplateDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailTemplateDefinition:
        """Test EmailTemplateDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailTemplateDefinition`
        """
        model = EmailTemplateDefinition()
        if include_optional:
            return EmailTemplateDefinition(
                email_template_id = '',
                default_test_data = {
                    'key' : null
                    },
                default_translations_by_locale = {
                    'key' : {
                        'key' : ''
                        }
                    },
                default_ejs = ''
            )
        else:
            return EmailTemplateDefinition(
                email_template_id = '',
                default_test_data = {
                    'key' : null
                    },
                default_translations_by_locale = {
                    'key' : {
                        'key' : ''
                        }
                    },
                default_ejs = '',
        )
        """

    def testEmailTemplateDefinition(self):
        """Test EmailTemplateDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
