# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.create_vote_response import CreateVoteResponse

class TestCreateVoteResponse(unittest.TestCase):
    """CreateVoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateVoteResponse:
        """Test CreateVoteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateVoteResponse`
        """
        model = CreateVoteResponse()
        if include_optional:
            return CreateVoteResponse(
                status = 'success'
            )
        else:
            return CreateVoteResponse(
                status = 'success',
        )
        """

    def testCreateVoteResponse(self):
        """Test CreateVoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
