# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.comment_log_data import CommentLogData

class TestCommentLogData(unittest.TestCase):
    """CommentLogData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommentLogData:
        """Test CommentLogData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommentLogData`
        """
        model = CommentLogData()
        if include_optional:
            return CommentLogData(
                clear_content = True,
                is_deleted_user = True,
                phrase = '',
                bad_word = '',
                word = '',
                locale = '',
                tenant_badge_id = '',
                badge_id = '',
                was_logged_in = True,
                found_user = True,
                verified = True,
                engine = '',
                engine_response = '',
                engine_tokens = 1.337,
                trust_factor = 1.337,
                rule = client.models.spam_rule.SpamRule(
                    actions = [
                        'spam'
                        ], 
                    comment_contains = '', ),
                user_id = '',
                subscribers = 1.337,
                notification_count = 1.337,
                votes_before = 1.337,
                votes_up_before = 1.337,
                votes_down_before = 1.337,
                votes_after = 1.337,
                votes_up_after = 1.337,
                votes_down_after = 1.337,
                repeat_action = 0,
                reason = 0,
                other_data = None,
                spam_before = True,
                spam_after = True,
                permanent_flag = 'permanent',
                approved_before = True,
                approved_after = True,
                reviewed_before = True,
                reviewed_after = True,
                text_before = '',
                text_after = '',
                expire_before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expire_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                flag_count_before = 1.337,
                trust_factor_before = 1.337,
                trust_factor_after = 1.337,
                referenced_comment_id = '',
                invalid_locale = '',
                detected_locale = '',
                detected_language = ''
            )
        else:
            return CommentLogData(
        )
        """

    def testCommentLogData(self):
        """Test CommentLogData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
