# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.user import User

class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> User:
        """Test User
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `User`
        """
        model = User()
        if include_optional:
            return User(
                id = '',
                tenant_id = '',
                username = '',
                display_name = '',
                website_url = '',
                email = '',
                pending_email = '',
                sign_up_date = 56,
                created_from_url_id = '',
                created_from_tenant_id = '',
                created_from_ip_hashed = '',
                verified = True,
                login_id = '',
                login_id_date = 56,
                login_count = 56,
                opted_in_notifications = True,
                opted_in_tenant_notifications = True,
                hide_account_code = True,
                avatar_src = '',
                is_fast_comments_help_request_admin = True,
                is_help_request_admin = True,
                is_account_owner = True,
                is_admin_admin = True,
                is_billing_admin = True,
                is_analytics_admin = True,
                is_customization_admin = True,
                is_manage_data_admin = True,
                is_comment_moderator_admin = True,
                is_api_admin = True,
                moderator_ids = [
                    ''
                    ],
                is_impersonator = True,
                is_coupon_manager = True,
                locale = '',
                digest_email_frequency = -1,
                ignored_add_to_my_site_messages = True,
                last_login_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                display_label = '',
                is_profile_activity_private = True,
                is_profile_comments_private = True,
                is_profile_dm_disabled = True,
                profile_comment_approval_mode = 1.337,
                karma = 1.337,
                password_hash = '',
                average_ticket_ack_time_ms = 1.337,
                has_blocked_users = True,
                bio = '',
                header_background_src = '',
                country_code = '',
                country_flag = '',
                social_links = [
                    ''
                    ],
                has_two_factor = True
            )
        else:
            return User(
                id = '',
                username = '',
                email = '',
                sign_up_date = 56,
                created_from_tenant_id = '',
                created_from_ip_hashed = '',
                verified = True,
                login_id = '',
                login_id_date = 56,
        )
        """

    def testUser(self):
        """Test User"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
