# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.aggregation_response import AggregationResponse

class TestAggregationResponse(unittest.TestCase):
    """AggregationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AggregationResponse:
        """Test AggregationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AggregationResponse`
        """
        model = AggregationResponse()
        if include_optional:
            return AggregationResponse(
                status = 'success',
                data = [
                    null
                    ],
                stats = client.models.aggregation_response_stats.AggregationResponse_stats(
                    time_ms = 56, 
                    scanned = 56, )
            )
        else:
            return AggregationResponse(
                status = 'success',
                data = [
                    null
                    ],
        )
        """

    def testAggregationResponse(self):
        """Test AggregationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
