# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pick_f_comment_public_comment_fields_keys import PickFCommentPublicCommentFieldsKeys

class TestPickFCommentPublicCommentFieldsKeys(unittest.TestCase):
    """PickFCommentPublicCommentFieldsKeys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PickFCommentPublicCommentFieldsKeys:
        """Test PickFCommentPublicCommentFieldsKeys
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PickFCommentPublicCommentFieldsKeys`
        """
        model = PickFCommentPublicCommentFieldsKeys()
        if include_optional:
            return PickFCommentPublicCommentFieldsKeys(
                id = '',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user_id = '',
                anon_user_id = '',
                commenter_name = '',
                commenter_link = '',
                comment_html = '',
                parent_id = '',
                votes = 56,
                votes_up = 56,
                votes_down = 56,
                verified = True,
                avatar_src = '',
                is_spam = True,
                has_images = True,
                is_deleted = True,
                is_deleted_user = True,
                is_by_admin = True,
                is_by_moderator = True,
                is_pinned = True,
                is_locked = True,
                rating = 1.337,
                display_label = '',
                badges = [
                    openapi_client.models.comment_user_badge_info.CommentUserBadgeInfo(
                        id = '', 
                        type = 1.337, 
                        description = '', 
                        display_label = '', 
                        display_src = '', 
                        background_color = '', 
                        border_color = '', 
                        text_color = '', 
                        css_class = '', )
                    ],
                feedback_ids = [
                    ''
                    ],
                view_count = 1.337,
                requires_verification = True,
                edit_key = ''
            )
        else:
            return PickFCommentPublicCommentFieldsKeys(
                id = '',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                commenter_name = '',
                comment_html = '',
                verified = True,
        )
        """

    def testPickFCommentPublicCommentFieldsKeys(self):
        """Test PickFCommentPublicCommentFieldsKeys"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
