# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.update_feed_post_params import UpdateFeedPostParams

class TestUpdateFeedPostParams(unittest.TestCase):
    """UpdateFeedPostParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateFeedPostParams:
        """Test UpdateFeedPostParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateFeedPostParams`
        """
        model = UpdateFeedPostParams()
        if include_optional:
            return UpdateFeedPostParams(
                title = '',
                content_html = '',
                media = [
                    client.models.feed_post_media_item.FeedPostMediaItem(
                        title = '', 
                        link_url = '', 
                        sizes = [
                            client.models.feed_post_media_item_asset.FeedPostMediaItemAsset(
                                w = 56, 
                                h = 56, 
                                src = '', )
                            ], )
                    ],
                links = [
                    client.models.feed_post_link.FeedPostLink(
                        text = '', 
                        title = '', 
                        description = '', 
                        url = '', )
                    ],
                tags = [
                    ''
                    ],
                meta = {
                    'key' : ''
                    }
            )
        else:
            return UpdateFeedPostParams(
        )
        """

    def testUpdateFeedPostParams(self):
        """Test UpdateFeedPostParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
