# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.find_comments_by_range_response import FindCommentsByRangeResponse

class TestFindCommentsByRangeResponse(unittest.TestCase):
    """FindCommentsByRangeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindCommentsByRangeResponse:
        """Test FindCommentsByRangeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindCommentsByRangeResponse`
        """
        model = FindCommentsByRangeResponse()
        if include_optional:
            return FindCommentsByRangeResponse(
                results = [
                    generated.models.find_comments_by_range_item.FindCommentsByRangeItem(
                        comment = null, 
                        result = generated.models.question_result.QuestionResult(
                            _id = '', 
                            tenant_id = '', 
                            url_id = '', 
                            anon_user_id = '', 
                            user_id = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            value = 56, 
                            comment_id = '', 
                            question_id = '', 
                            meta = [
                                generated.models.meta_item.MetaItem(
                                    name = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            ip_hash = '', ), )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FindCommentsByRangeResponse(
                results = [
                    generated.models.find_comments_by_range_item.FindCommentsByRangeItem(
                        comment = null, 
                        result = generated.models.question_result.QuestionResult(
                            _id = '', 
                            tenant_id = '', 
                            url_id = '', 
                            anon_user_id = '', 
                            user_id = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            value = 56, 
                            comment_id = '', 
                            question_id = '', 
                            meta = [
                                generated.models.meta_item.MetaItem(
                                    name = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            ip_hash = '', ), )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testFindCommentsByRangeResponse(self):
        """Test FindCommentsByRangeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
