# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.create_tenant_user_body import CreateTenantUserBody

class TestCreateTenantUserBody(unittest.TestCase):
    """CreateTenantUserBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTenantUserBody:
        """Test CreateTenantUserBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTenantUserBody`
        """
        model = CreateTenantUserBody()
        if include_optional:
            return CreateTenantUserBody(
                username = '',
                email = '',
                display_name = '',
                website_url = '',
                sign_up_date = 1.337,
                locale = '',
                verified = True,
                login_count = 1.337,
                opted_in_notifications = True,
                opted_in_tenant_notifications = True,
                hide_account_code = True,
                avatar_src = '',
                is_help_request_admin = True,
                is_account_owner = True,
                is_admin_admin = True,
                is_billing_admin = True,
                is_analytics_admin = True,
                is_customization_admin = True,
                is_manage_data_admin = True,
                is_comment_moderator_admin = True,
                is_api_admin = True,
                moderator_ids = [
                    ''
                    ],
                digest_email_frequency = 1.337,
                display_label = ''
            )
        else:
            return CreateTenantUserBody(
                username = '',
                email = '',
        )
        """

    def testCreateTenantUserBody(self):
        """Test CreateTenantUserBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
