# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.banned_user_match_matched_on_value import BannedUserMatchMatchedOnValue

class TestBannedUserMatchMatchedOnValue(unittest.TestCase):
    """BannedUserMatchMatchedOnValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BannedUserMatchMatchedOnValue:
        """Test BannedUserMatchMatchedOnValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BannedUserMatchMatchedOnValue`
        """
        model = BannedUserMatchMatchedOnValue()
        if include_optional:
            return BannedUserMatchMatchedOnValue(
            )
        else:
            return BannedUserMatchMatchedOnValue(
        )
        """

    def testBannedUserMatchMatchedOnValue(self):
        """Test BannedUserMatchMatchedOnValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
