# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.custom_email_template import CustomEmailTemplate

class TestCustomEmailTemplate(unittest.TestCase):
    """CustomEmailTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomEmailTemplate:
        """Test CustomEmailTemplate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomEmailTemplate`
        """
        model = CustomEmailTemplate()
        if include_optional:
            return CustomEmailTemplate(
                id = '',
                tenant_id = '',
                email_template_id = '',
                display_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by_user_id = '',
                domain = '',
                ejs = '',
                translation_overrides_by_locale = {
                    'key' : {
                        'key' : ''
                        }
                    },
                test_data = None
            )
        else:
            return CustomEmailTemplate(
                id = '',
                tenant_id = '',
                email_template_id = '',
                display_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by_user_id = '',
                ejs = '',
                translation_overrides_by_locale = {
                    'key' : {
                        'key' : ''
                        }
                    },
                test_data = None,
        )
        """

    def testCustomEmailTemplate(self):
        """Test CustomEmailTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
