# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.update_subscription_api_response import UpdateSubscriptionAPIResponse

class TestUpdateSubscriptionAPIResponse(unittest.TestCase):
    """UpdateSubscriptionAPIResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSubscriptionAPIResponse:
        """Test UpdateSubscriptionAPIResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateSubscriptionAPIResponse`
        """
        model = UpdateSubscriptionAPIResponse()
        if include_optional:
            return UpdateSubscriptionAPIResponse(
                reason = '',
                code = '',
                subscription = client.models.api_user_subscription.APIUserSubscription(
                    notification_frequency = 1.337, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    page_title = '', 
                    url = '', 
                    url_id = '', 
                    anon_user_id = '', 
                    user_id = '', 
                    id = '', ),
                status = ''
            )
        else:
            return UpdateSubscriptionAPIResponse(
                status = '',
        )
        """

    def testUpdateSubscriptionAPIResponse(self):
        """Test UpdateSubscriptionAPIResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
