# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.public_api_delete_comment_response import PublicAPIDeleteCommentResponse

class TestPublicAPIDeleteCommentResponse(unittest.TestCase):
    """PublicAPIDeleteCommentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicAPIDeleteCommentResponse:
        """Test PublicAPIDeleteCommentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicAPIDeleteCommentResponse`
        """
        model = PublicAPIDeleteCommentResponse()
        if include_optional:
            return PublicAPIDeleteCommentResponse(
                comment = generated.models.pick_f_comment/is_deleted_or_comment_html_or_commenter_name_or_user_id_.Pick_FComment.isDeleted-or-commentHTML-or-commenterName-or-userId_(
                    user_id = '', 
                    commenter_name = '', 
                    comment_html = '', 
                    is_deleted = True, ),
                hard_removed = True,
                status = 'success'
            )
        else:
            return PublicAPIDeleteCommentResponse(
                hard_removed = True,
                status = 'success',
        )
        """

    def testPublicAPIDeleteCommentResponse(self):
        """Test PublicAPIDeleteCommentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
