# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.update_user_badge_params import UpdateUserBadgeParams

class TestUpdateUserBadgeParams(unittest.TestCase):
    """UpdateUserBadgeParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserBadgeParams:
        """Test UpdateUserBadgeParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserBadgeParams`
        """
        model = UpdateUserBadgeParams()
        if include_optional:
            return UpdateUserBadgeParams(
                displayed_on_comments = True
            )
        else:
            return UpdateUserBadgeParams(
        )
        """

    def testUpdateUserBadgeParams(self):
        """Test UpdateUserBadgeParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
