# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.moderation_page_search_response import ModerationPageSearchResponse

class TestModerationPageSearchResponse(unittest.TestCase):
    """ModerationPageSearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModerationPageSearchResponse:
        """Test ModerationPageSearchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModerationPageSearchResponse`
        """
        model = ModerationPageSearchResponse()
        if include_optional:
            return ModerationPageSearchResponse(
                pages = [
                    client.models.moderation_page_search_projected.ModerationPageSearchProjected(
                        url_id = '', 
                        url = '', 
                        title = '', 
                        comment_count = 1.337, )
                    ],
                status = 'success'
            )
        else:
            return ModerationPageSearchResponse(
                pages = [
                    client.models.moderation_page_search_projected.ModerationPageSearchProjected(
                        url_id = '', 
                        url = '', 
                        title = '', 
                        comment_count = 1.337, )
                    ],
                status = 'success',
        )
        """

    def testModerationPageSearchResponse(self):
        """Test ModerationPageSearchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
