# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.user_badge import UserBadge

class TestUserBadge(unittest.TestCase):
    """UserBadge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserBadge:
        """Test UserBadge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserBadge`
        """
        model = UserBadge()
        if include_optional:
            return UserBadge(
                id = '',
                user_id = '',
                badge_id = '',
                from_tenant_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 56,
                threshold = 56,
                description = '',
                display_label = '',
                display_src = '',
                background_color = '',
                border_color = '',
                text_color = '',
                css_class = '',
                veteran_user_threshold_millis = 56,
                displayed_on_comments = True,
                received_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                order = 56
            )
        else:
            return UserBadge(
                id = '',
                user_id = '',
                badge_id = '',
                from_tenant_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 56,
                threshold = 56,
                description = '',
                display_label = '',
                veteran_user_threshold_millis = 56,
                displayed_on_comments = True,
                received_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testUserBadge(self):
        """Test UserBadge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
