# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.pub_sub_comment import PubSubComment

class TestPubSubComment(unittest.TestCase):
    """PubSubComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PubSubComment:
        """Test PubSubComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PubSubComment`
        """
        model = PubSubComment()
        if include_optional:
            return PubSubComment(
                var_date = '',
                id = '',
                tenant_id = '',
                url_id = '',
                url = '',
                page_title = '',
                user_id = '',
                anon_user_id = '',
                commenter_name = '',
                commenter_link = '',
                comment = '',
                comment_html = '',
                parent_id = '',
                votes = 56,
                votes_up = 56,
                votes_down = 56,
                expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verified = True,
                reviewed = True,
                avatar_src = '',
                is_spam = True,
                has_images = True,
                has_links = True,
                has_code = True,
                approved = True,
                locale = '',
                is_deleted = True,
                is_deleted_user = True,
                is_banned_user = True,
                is_by_admin = True,
                is_by_moderator = True,
                is_pinned = True,
                is_locked = True,
                flag_count = 56,
                rating = 1.337,
                display_label = '',
                badges = [
                    client.models.comment_user_badge_info.CommentUserBadgeInfo(
                        id = '', 
                        type = 56, 
                        description = '', 
                        display_label = '', 
                        display_src = '', 
                        background_color = '', 
                        border_color = '', 
                        text_color = '', 
                        css_class = '', )
                    ],
                domain = '',
                feedback_ids = [
                    ''
                    ],
                group_ids = [
                    ''
                    ],
                view_count = 56,
                is_live = True,
                hidden = True
            )
        else:
            return PubSubComment(
                var_date = '',
                id = '',
                tenant_id = '',
                url_id = '',
                url = '',
                commenter_name = '',
                comment = '',
                comment_html = '',
                verified = True,
                approved = True,
                locale = '',
        )
        """

    def testPubSubComment(self):
        """Test PubSubComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
