# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.get_comments200_response import GetComments200Response

class TestGetComments200Response(unittest.TestCase):
    """GetComments200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetComments200Response:
        """Test GetComments200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetComments200Response`
        """
        model = GetComments200Response()
        if include_optional:
            return GetComments200Response(
                status = 'failed',
                comments = [
                    client.models.pick_f_comment/api_comment_fields_keys_.Pick_FComment.APICommentFieldsKeys_(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        _id = '', 
                        tenant_id = '', 
                        url_id = '', 
                        url_id_raw = '', 
                        url = '', 
                        page_title = '', 
                        user_id = '', 
                        anon_user_id = '', 
                        commenter_email = '', 
                        commenter_name = '', 
                        commenter_link = '', 
                        comment = '', 
                        comment_html = '', 
                        parent_id = '', 
                        local_date_string = '', 
                        local_date_hours = 56, 
                        votes = 56, 
                        votes_up = 56, 
                        votes_down = 56, 
                        expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        verified = True, 
                        verified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        notification_sent_for_parent = True, 
                        notification_sent_for_parent_tenant = True, 
                        reviewed = True, 
                        external_id = '', 
                        external_parent_id = '', 
                        avatar_src = '', 
                        is_spam = True, 
                        ai_determined_spam = True, 
                        has_images = True, 
                        has_links = True, 
                        has_code = True, 
                        approved = True, 
                        locale = '', 
                        is_deleted = True, 
                        is_deleted_user = True, 
                        is_by_admin = True, 
                        is_by_moderator = True, 
                        is_pinned = True, 
                        is_locked = True, 
                        flag_count = 56, 
                        rating = 1.337, 
                        display_label = '', 
                        from_product_id = 56, 
                        meta = {
                            'key' : null
                            }, 
                        mentions = [
                            client.models.comment_user_mention_info.CommentUserMentionInfo(
                                id = '', 
                                tag = '', 
                                raw_tag = '', 
                                type = 'user', 
                                sent = True, )
                            ], 
                        hash_tags = [
                            client.models.comment_user_hash_tag_info.CommentUserHashTagInfo(
                                id = '', 
                                tag = '', 
                                url = '', 
                                retain = True, )
                            ], 
                        badges = [
                            client.models.comment_user_badge_info.CommentUserBadgeInfo(
                                id = '', 
                                type = 56, 
                                description = '', 
                                display_label = '', 
                                display_src = '', 
                                background_color = '', 
                                border_color = '', 
                                text_color = '', 
                                css_class = '', )
                            ], 
                        domain = '', 
                        moderation_group_ids = [
                            ''
                            ], 
                        feedback_ids = [
                            ''
                            ], )
                    ],
                reason = '',
                code = '',
                secondary_code = '',
                banned_until = 56,
                max_character_length = 56,
                translated_error = '',
                custom_config = client.models.custom_config_parameters.CustomConfigParameters(
                    absolute_and_relative_dates = True, 
                    absolute_dates = True, 
                    allow_anon = True, 
                    allow_anon_flag = True, 
                    allow_anon_votes = True, 
                    allowed_languages = [
                        ''
                        ], 
                    collapse_replies = True, 
                    comment_count_format = '', 
                    comment_html_rendering_mode = 0, 
                    comment_thread_delete_mode = null, 
                    commenter_name_format = null, 
                    count_above_toggle = 56, 
                    custom_css = '', 
                    default_avatar_src = '', 
                    default_sort_direction = null, 
                    default_username = '', 
                    disable_auto_admin_migration = True, 
                    disable_auto_hash_tag_creation = True, 
                    disable_blocking = True, 
                    disable_commenter_comment_delete = True, 
                    disable_commenter_comment_edit = True, 
                    disable_email_inputs = True, 
                    disable_live_commenting = True, 
                    disable_notification_bell = True, 
                    disable_profiles = True, 
                    disable_success_message = True, 
                    disable_toolbar = True, 
                    disable_unverified_label = True, 
                    disable_voting = True, 
                    enable_commenter_links = True, 
                    enable_search = True, 
                    enable_spoilers = True, 
                    enable_third_party_cookie_bypass = True, 
                    enable_view_counts = True, 
                    enable_vote_list = True, 
                    enable_wysiwyg = True, 
                    gif_rating = 'g', 
                    has_dark_background = True, 
                    header_html = '', 
                    hide_avatars = True, 
                    hide_comments_under_count_text_format = '', 
                    image_content_profanity_level = 'off', 
                    input_after_comments = True, 
                    limit_comments_by_groups = True, 
                    locale = '', 
                    max_comment_character_length = 56, 
                    max_comment_created_count_pupm = 56, 
                    no_custom_config = True, 
                    no_image_uploads = True, 
                    no_styles = True, 
                    page_size = 56, 
                    readonly = True, 
                    require_sso = True, 
                    enable_resize_handle = True, 
                    restricted_link_domains = [
                        ''
                        ], 
                    show_badges_in_top_bar = True, 
                    show_comment_save_success = True, 
                    show_live_right_away = True, 
                    show_question = True, 
                    spam_rules = [
                        client.models.spam_rule.SpamRule(
                            actions = [
                                'spam'
                                ], 
                            comment_contains = '', )
                        ], 
                    sso_sec_lvl = 0, 
                    translations = null, 
                    use_show_comments_toggle = True, 
                    use_single_line_comment_input = True, 
                    vote_style = 0, 
                    widget_question_id = '', 
                    widget_question_results_style = 0, 
                    widget_question_style = 0, 
                    widget_question_when_to_save = 0, 
                    widget_questions_required = 0, 
                    widget_sub_question_visibility = 0, 
                    wrap = True, )
            )
        else:
            return GetComments200Response(
                status = 'failed',
                comments = [
                    client.models.pick_f_comment/api_comment_fields_keys_.Pick_FComment.APICommentFieldsKeys_(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        _id = '', 
                        tenant_id = '', 
                        url_id = '', 
                        url_id_raw = '', 
                        url = '', 
                        page_title = '', 
                        user_id = '', 
                        anon_user_id = '', 
                        commenter_email = '', 
                        commenter_name = '', 
                        commenter_link = '', 
                        comment = '', 
                        comment_html = '', 
                        parent_id = '', 
                        local_date_string = '', 
                        local_date_hours = 56, 
                        votes = 56, 
                        votes_up = 56, 
                        votes_down = 56, 
                        expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        verified = True, 
                        verified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        notification_sent_for_parent = True, 
                        notification_sent_for_parent_tenant = True, 
                        reviewed = True, 
                        external_id = '', 
                        external_parent_id = '', 
                        avatar_src = '', 
                        is_spam = True, 
                        ai_determined_spam = True, 
                        has_images = True, 
                        has_links = True, 
                        has_code = True, 
                        approved = True, 
                        locale = '', 
                        is_deleted = True, 
                        is_deleted_user = True, 
                        is_by_admin = True, 
                        is_by_moderator = True, 
                        is_pinned = True, 
                        is_locked = True, 
                        flag_count = 56, 
                        rating = 1.337, 
                        display_label = '', 
                        from_product_id = 56, 
                        meta = {
                            'key' : null
                            }, 
                        mentions = [
                            client.models.comment_user_mention_info.CommentUserMentionInfo(
                                id = '', 
                                tag = '', 
                                raw_tag = '', 
                                type = 'user', 
                                sent = True, )
                            ], 
                        hash_tags = [
                            client.models.comment_user_hash_tag_info.CommentUserHashTagInfo(
                                id = '', 
                                tag = '', 
                                url = '', 
                                retain = True, )
                            ], 
                        badges = [
                            client.models.comment_user_badge_info.CommentUserBadgeInfo(
                                id = '', 
                                type = 56, 
                                description = '', 
                                display_label = '', 
                                display_src = '', 
                                background_color = '', 
                                border_color = '', 
                                text_color = '', 
                                css_class = '', )
                            ], 
                        domain = '', 
                        moderation_group_ids = [
                            ''
                            ], 
                        feedback_ids = [
                            ''
                            ], )
                    ],
                reason = '',
                code = '',
        )
        """

    def testGetComments200Response(self):
        """Test GetComments200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
