# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.comment_text_update_request import CommentTextUpdateRequest

class TestCommentTextUpdateRequest(unittest.TestCase):
    """CommentTextUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommentTextUpdateRequest:
        """Test CommentTextUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommentTextUpdateRequest`
        """
        model = CommentTextUpdateRequest()
        if include_optional:
            return CommentTextUpdateRequest(
                comment = '',
                mentions = [
                    generated.models.comment_user_mention_info.CommentUserMentionInfo(
                        id = '', 
                        tag = '', 
                        raw_tag = '', 
                        type = 'user', 
                        sent = True, )
                    ],
                hash_tags = [
                    generated.models.comment_user_hash_tag_info.CommentUserHashTagInfo(
                        id = '', 
                        tag = '', 
                        url = '', 
                        retain = True, )
                    ]
            )
        else:
            return CommentTextUpdateRequest(
                comment = '',
        )
        """

    def testCommentTextUpdateRequest(self):
        """Test CommentTextUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
