# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.moderation_api_child_comments_response import ModerationAPIChildCommentsResponse

class TestModerationAPIChildCommentsResponse(unittest.TestCase):
    """ModerationAPIChildCommentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModerationAPIChildCommentsResponse:
        """Test ModerationAPIChildCommentsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModerationAPIChildCommentsResponse`
        """
        model = ModerationAPIChildCommentsResponse()
        if include_optional:
            return ModerationAPIChildCommentsResponse(
                comments = [
                    client.models.moderation_api_comment.ModerationAPIComment(
                        is_local_deleted = True, 
                        reply_count = 1.337, 
                        feedback_results = [
                            ''
                            ], 
                        is_voted_up = True, 
                        is_voted_down = True, 
                        my_vote_id = '', 
                        _id = '', 
                        tenant_id = '', 
                        url_id = '', 
                        url = '', 
                        page_title = '', 
                        user_id = null, 
                        anon_user_id = '', 
                        commenter_name = '', 
                        commenter_link = '', 
                        comment_html = '', 
                        parent_id = '', 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        local_date_string = '', 
                        votes = 1.337, 
                        votes_up = 1.337, 
                        votes_down = 1.337, 
                        expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reviewed = True, 
                        avatar_src = '', 
                        is_spam = True, 
                        perm_not_spam = True, 
                        has_links = True, 
                        has_code = True, 
                        approved = True, 
                        locale = '', 
                        is_banned_user = True, 
                        is_by_admin = True, 
                        is_by_moderator = True, 
                        is_pinned = True, 
                        is_locked = True, 
                        flag_count = 1.337, 
                        display_label = '', 
                        badges = [
                            client.models.comment_user_badge_info.CommentUserBadgeInfo(
                                id = '', 
                                type = 56, 
                                description = '', 
                                display_label = '', 
                                display_src = '', 
                                background_color = '', 
                                border_color = '', 
                                text_color = '', 
                                css_class = '', )
                            ], 
                        verified = True, 
                        feedback_ids = [
                            ''
                            ], 
                        is_deleted = True, )
                    ],
                status = 'success'
            )
        else:
            return ModerationAPIChildCommentsResponse(
                comments = [
                    client.models.moderation_api_comment.ModerationAPIComment(
                        is_local_deleted = True, 
                        reply_count = 1.337, 
                        feedback_results = [
                            ''
                            ], 
                        is_voted_up = True, 
                        is_voted_down = True, 
                        my_vote_id = '', 
                        _id = '', 
                        tenant_id = '', 
                        url_id = '', 
                        url = '', 
                        page_title = '', 
                        user_id = null, 
                        anon_user_id = '', 
                        commenter_name = '', 
                        commenter_link = '', 
                        comment_html = '', 
                        parent_id = '', 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        local_date_string = '', 
                        votes = 1.337, 
                        votes_up = 1.337, 
                        votes_down = 1.337, 
                        expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reviewed = True, 
                        avatar_src = '', 
                        is_spam = True, 
                        perm_not_spam = True, 
                        has_links = True, 
                        has_code = True, 
                        approved = True, 
                        locale = '', 
                        is_banned_user = True, 
                        is_by_admin = True, 
                        is_by_moderator = True, 
                        is_pinned = True, 
                        is_locked = True, 
                        flag_count = 1.337, 
                        display_label = '', 
                        badges = [
                            client.models.comment_user_badge_info.CommentUserBadgeInfo(
                                id = '', 
                                type = 56, 
                                description = '', 
                                display_label = '', 
                                display_src = '', 
                                background_color = '', 
                                border_color = '', 
                                text_color = '', 
                                css_class = '', )
                            ], 
                        verified = True, 
                        feedback_ids = [
                            ''
                            ], 
                        is_deleted = True, )
                    ],
                status = 'success',
        )
        """

    def testModerationAPIChildCommentsResponse(self):
        """Test ModerationAPIChildCommentsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
