# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sso_security_level import SSOSecurityLevel

class TestSSOSecurityLevel(unittest.TestCase):
    """SSOSecurityLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSOSecurityLevel(self):
        """Test SSOSecurityLevel"""
        # inst = SSOSecurityLevel()

if __name__ == '__main__':
    unittest.main()
