# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.comment_log_type import CommentLogType

class TestCommentLogType(unittest.TestCase):
    """CommentLogType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommentLogType(self):
        """Test CommentLogType"""
        # inst = CommentLogType()

if __name__ == '__main__':
    unittest.main()
