# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.update_tenant_package_body import UpdateTenantPackageBody

class TestUpdateTenantPackageBody(unittest.TestCase):
    """UpdateTenantPackageBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTenantPackageBody:
        """Test UpdateTenantPackageBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTenantPackageBody`
        """
        model = UpdateTenantPackageBody()
        if include_optional:
            return UpdateTenantPackageBody(
                name = '',
                monthly_cost_usd = 1.337,
                yearly_cost_usd = 1.337,
                max_monthly_page_loads = 1.337,
                max_monthly_api_credits = 1.337,
                max_monthly_comments = 1.337,
                max_concurrent_users = 1.337,
                max_tenant_users = 1.337,
                max_sso_users = 1.337,
                max_moderators = 1.337,
                max_domains = 1.337,
                has_debranding = True,
                has_white_labeling = True,
                for_who_text = '',
                feature_taglines = [
                    ''
                    ],
                has_flex_pricing = True,
                flex_page_load_cost_cents = 1.337,
                flex_page_load_unit = 1.337,
                flex_comment_cost_cents = 1.337,
                flex_comment_unit = 1.337,
                flex_sso_user_cost_cents = 1.337,
                flex_sso_user_unit = 1.337,
                flex_api_credit_cost_cents = 1.337,
                flex_api_credit_unit = 1.337,
                flex_moderator_cost_cents = 1.337,
                flex_moderator_unit = 1.337,
                flex_admin_cost_cents = 1.337,
                flex_admin_unit = 1.337,
                flex_domain_cost_cents = 1.337,
                flex_domain_unit = 1.337,
                flex_minimum_cost_cents = 1.337
            )
        else:
            return UpdateTenantPackageBody(
        )
        """

    def testUpdateTenantPackageBody(self):
        """Test UpdateTenantPackageBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
