# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.public_api_set_comment_text_response import PublicAPISetCommentTextResponse

class TestPublicAPISetCommentTextResponse(unittest.TestCase):
    """PublicAPISetCommentTextResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicAPISetCommentTextResponse:
        """Test PublicAPISetCommentTextResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicAPISetCommentTextResponse`
        """
        model = PublicAPISetCommentTextResponse()
        if include_optional:
            return PublicAPISetCommentTextResponse(
                comment = client.models.set_comment_text_result.SetCommentTextResult(
                    approved = True, 
                    comment_html = '', ),
                status = 'success'
            )
        else:
            return PublicAPISetCommentTextResponse(
                comment = client.models.set_comment_text_result.SetCommentTextResult(
                    approved = True, 
                    comment_html = '', ),
                status = 'success',
        )
        """

    def testPublicAPISetCommentTextResponse(self):
        """Test PublicAPISetCommentTextResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
