# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.get_comment_vote_user_names_success_response import GetCommentVoteUserNamesSuccessResponse

class TestGetCommentVoteUserNamesSuccessResponse(unittest.TestCase):
    """GetCommentVoteUserNamesSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCommentVoteUserNamesSuccessResponse:
        """Test GetCommentVoteUserNamesSuccessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCommentVoteUserNamesSuccessResponse`
        """
        model = GetCommentVoteUserNamesSuccessResponse()
        if include_optional:
            return GetCommentVoteUserNamesSuccessResponse(
                status = 'success',
                vote_user_names = [
                    ''
                    ],
                has_more = True
            )
        else:
            return GetCommentVoteUserNamesSuccessResponse(
                status = 'success',
                vote_user_names = [
                    ''
                    ],
                has_more = True,
        )
        """

    def testGetCommentVoteUserNamesSuccessResponse(self):
        """Test GetCommentVoteUserNamesSuccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
