# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from generated.models.search_users_response import SearchUsersResponse

class TestSearchUsersResponse(unittest.TestCase):
    """SearchUsersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchUsersResponse:
        """Test SearchUsersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchUsersResponse`
        """
        model = SearchUsersResponse()
        if include_optional:
            return SearchUsersResponse(
                status = 'success',
                users = [
                    generated.models.user_search_result.UserSearchResult(
                        id = '', 
                        name = '', 
                        display_name = '', 
                        avatar_src = '', 
                        type = 'user', )
                    ]
            )
        else:
            return SearchUsersResponse(
                status = 'success',
                users = [
                    generated.models.user_search_result.UserSearchResult(
                        id = '', 
                        name = '', 
                        display_name = '', 
                        avatar_src = '', 
                        type = 'user', )
                    ],
        )
        """

    def testSearchUsersResponse(self):
        """Test SearchUsersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
