# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from client.models.create_question_config_response import CreateQuestionConfigResponse

class TestCreateQuestionConfigResponse(unittest.TestCase):
    """CreateQuestionConfigResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateQuestionConfigResponse:
        """Test CreateQuestionConfigResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateQuestionConfigResponse`
        """
        model = CreateQuestionConfigResponse()
        if include_optional:
            return CreateQuestionConfigResponse(
                status = 'success',
                question_config = client.models.question_config.QuestionConfig(
                    _id = '', 
                    tenant_id = '', 
                    name = '', 
                    question = '', 
                    summary_label = '', 
                    help_text = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by = '', 
                    used_count = 1.337, 
                    last_used = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    type = '', 
                    num_stars = 1.337, 
                    min = 1.337, 
                    max = 1.337, 
                    default_value = 1.337, 
                    label_negative = '', 
                    label_positive = '', 
                    custom_options = [
                        client.models.question_config_custom_options_inner.QuestionConfig_customOptions_inner(
                            image_src = '', 
                            name = '', )
                        ], 
                    sub_question_ids = [
                        ''
                        ], 
                    always_show_sub_questions = True, 
                    reporting_order = 1.337, )
            )
        else:
            return CreateQuestionConfigResponse(
                status = 'success',
                question_config = client.models.question_config.QuestionConfig(
                    _id = '', 
                    tenant_id = '', 
                    name = '', 
                    question = '', 
                    summary_label = '', 
                    help_text = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by = '', 
                    used_count = 1.337, 
                    last_used = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    type = '', 
                    num_stars = 1.337, 
                    min = 1.337, 
                    max = 1.337, 
                    default_value = 1.337, 
                    label_negative = '', 
                    label_positive = '', 
                    custom_options = [
                        client.models.question_config_custom_options_inner.QuestionConfig_customOptions_inner(
                            image_src = '', 
                            name = '', )
                        ], 
                    sub_question_ids = [
                        ''
                        ], 
                    always_show_sub_questions = True, 
                    reporting_order = 1.337, ),
        )
        """

    def testCreateQuestionConfigResponse(self):
        """Test CreateQuestionConfigResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
