# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fastcomments_client.models.pin_comment200_response import PinComment200Response

class TestPinComment200Response(unittest.TestCase):
    """PinComment200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PinComment200Response:
        """Test PinComment200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PinComment200Response`
        """
        model = PinComment200Response()
        if include_optional:
            return PinComment200Response(
                comment_positions = {
                    'key' : openapi_client.models.record_string__before_string_or_null__after_string_or_null___value.Record_string__before_string_or_null__after_string_or_null___value(
                        after = '', 
                        before = '', )
                    },
                status = 'failed',
                reason = '',
                code = '',
                secondary_code = '',
                banned_until = 1.337,
                max_character_length = 1.337,
                translated_error = '',
                custom_config = openapi_client.models.custom_config_parameters.CustomConfigParameters(
                    absolute_and_relative_dates = True, 
                    absolute_dates = True, 
                    allow_anon = True, 
                    allow_anon_flag = True, 
                    allow_anon_votes = True, 
                    allowed_languages = [
                        ''
                        ], 
                    collapse_replies = True, 
                    comment_count_format = '', 
                    comment_html_rendering_mode = 0, 
                    comment_thread_delete_mode = null, 
                    commenter_name_format = null, 
                    count_above_toggle = 1.337, 
                    custom_css = '', 
                    default_avatar_src = '', 
                    default_sort_direction = null, 
                    default_username = '', 
                    disable_auto_admin_migration = True, 
                    disable_auto_hash_tag_creation = True, 
                    disable_blocking = True, 
                    disable_commenter_comment_delete = True, 
                    disable_commenter_comment_edit = True, 
                    disable_email_inputs = True, 
                    disable_live_commenting = True, 
                    disable_notification_bell = True, 
                    disable_profiles = True, 
                    disable_success_message = True, 
                    disable_toolbar = True, 
                    disable_unverified_label = True, 
                    disable_voting = True, 
                    enable_commenter_links = True, 
                    enable_search = True, 
                    enable_spoilers = True, 
                    enable_third_party_cookie_bypass = True, 
                    enable_view_counts = True, 
                    enable_vote_list = True, 
                    enable_wysiwyg = True, 
                    gif_rating = 'g', 
                    has_dark_background = True, 
                    header_html = '', 
                    hide_avatars = True, 
                    hide_comments_under_count_text_format = '', 
                    input_after_comments = True, 
                    limit_comments_by_groups = True, 
                    locale = '', 
                    max_comment_character_length = 1.337, 
                    max_comment_created_count_pupm = 1.337, 
                    no_custom_config = True, 
                    no_image_uploads = True, 
                    no_styles = True, 
                    page_size = 1.337, 
                    readonly = True, 
                    require_sso = True, 
                    sso_sec_lvl = 0, 
                    restricted_link_domains = [
                        ''
                        ], 
                    show_comment_save_success = True, 
                    show_live_right_away = True, 
                    show_question = True, 
                    spam_rules = [
                        openapi_client.models.spam_rule.SpamRule(
                            actions = [
                                'spam'
                                ], 
                            comment_contains = '', )
                        ], 
                    translations = null, 
                    use_show_comments_toggle = True, 
                    use_single_line_comment_input = True, 
                    vote_style = 0, 
                    widget_question_id = '', 
                    widget_question_results_style = 0, 
                    widget_question_style = 0, 
                    widget_question_when_to_save = 0, 
                    widget_questions_required = 0, 
                    widget_sub_question_visibility = 0, 
                    wrap = True, )
            )
        else:
            return PinComment200Response(
                comment_positions = {
                    'key' : openapi_client.models.record_string__before_string_or_null__after_string_or_null___value.Record_string__before_string_or_null__after_string_or_null___value(
                        after = '', 
                        before = '', )
                    },
                status = 'failed',
                reason = '',
                code = '',
        )
        """

    def testPinComment200Response(self):
        """Test PinComment200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
