# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fastcomments_client.models.update_domain_config_params import UpdateDomainConfigParams

class TestUpdateDomainConfigParams(unittest.TestCase):
    """UpdateDomainConfigParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateDomainConfigParams:
        """Test UpdateDomainConfigParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateDomainConfigParams`
        """
        model = UpdateDomainConfigParams()
        if include_optional:
            return UpdateDomainConfigParams(
                domain = '',
                email_from_name = '',
                email_from_email = '',
                logo_src = '',
                logo_src100px = '',
                footer_unsubscribe_url = '',
                email_headers = {
                    'key' : ''
                    }
            )
        else:
            return UpdateDomainConfigParams(
                domain = '',
        )
        """

    def testUpdateDomainConfigParams(self):
        """Test UpdateDomainConfigParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
