# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.aggregation_operation import AggregationOperation
from openapi_client.models.aggregation_request_sort import AggregationRequestSort
from openapi_client.models.query_predicate import QueryPredicate
from typing import Optional, Set
from typing_extensions import Self

class AggregationRequest(BaseModel):
    """
    The aggregation request accepts a resource, optional grouping keys, an array of operations, and an optional sort
    """ # noqa: E501
    query: Optional[List[QueryPredicate]] = None
    resource_name: StrictStr = Field(alias="resourceName")
    group_by: Optional[List[StrictStr]] = Field(default=None, alias="groupBy")
    operations: List[AggregationOperation]
    sort: Optional[AggregationRequestSort] = None
    __properties: ClassVar[List[str]] = ["query", "resourceName", "groupBy", "operations", "sort"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AggregationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in query (list)
        _items = []
        if self.query:
            for _item_query in self.query:
                if _item_query:
                    _items.append(_item_query.to_dict())
            _dict['query'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in operations (list)
        _items = []
        if self.operations:
            for _item_operations in self.operations:
                if _item_operations:
                    _items.append(_item_operations.to_dict())
            _dict['operations'] = _items
        # override the default output from pydantic by calling `to_dict()` of sort
        if self.sort:
            _dict['sort'] = self.sort.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AggregationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": [QueryPredicate.from_dict(_item) for _item in obj["query"]] if obj.get("query") is not None else None,
            "resourceName": obj.get("resourceName"),
            "groupBy": obj.get("groupBy"),
            "operations": [AggregationOperation.from_dict(_item) for _item in obj["operations"]] if obj.get("operations") is not None else None,
            "sort": AggregationRequestSort.from_dict(obj["sort"]) if obj.get("sort") is not None else None
        })
        return _obj


