# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.notification_type import NotificationType
from typing import Optional, Set
from typing_extensions import Self

class UserNotification(BaseModel):
    """
    UserNotification
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    tenant_id: StrictStr = Field(alias="tenantId")
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    anon_user_id: Optional[StrictStr] = Field(default=None, alias="anonUserId")
    url_id: StrictStr = Field(alias="urlId")
    url: StrictStr
    page_title: Optional[StrictStr] = Field(default=None, alias="pageTitle")
    related_object_type: Union[StrictFloat, StrictInt] = Field(alias="relatedObjectType")
    related_object_id: StrictStr = Field(alias="relatedObjectId")
    viewed: StrictBool
    is_unread_message: StrictBool = Field(alias="isUnreadMessage")
    sent: StrictBool
    created_at: datetime = Field(alias="createdAt")
    type: NotificationType
    from_comment_id: Optional[StrictStr] = Field(default=None, alias="fromCommentId")
    from_vote_id: Optional[StrictStr] = Field(default=None, alias="fromVoteId")
    from_user_name: Optional[StrictStr] = Field(default=None, alias="fromUserName")
    from_user_id: Optional[StrictStr] = Field(default=None, alias="fromUserId")
    from_user_avatar_src: Optional[StrictStr] = Field(default=None, alias="fromUserAvatarSrc")
    opted_out: StrictBool = Field(alias="optedOut")
    __properties: ClassVar[List[str]] = ["_id", "tenantId", "userId", "anonUserId", "urlId", "url", "pageTitle", "relatedObjectType", "relatedObjectId", "viewed", "isUnreadMessage", "sent", "createdAt", "type", "fromCommentId", "fromVoteId", "fromUserName", "fromUserId", "fromUserAvatarSrc", "optedOut"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserNotification from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['userId'] = None

        # set to None if anon_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.anon_user_id is None and "anon_user_id" in self.model_fields_set:
            _dict['anonUserId'] = None

        # set to None if page_title (nullable) is None
        # and model_fields_set contains the field
        if self.page_title is None and "page_title" in self.model_fields_set:
            _dict['pageTitle'] = None

        # set to None if from_comment_id (nullable) is None
        # and model_fields_set contains the field
        if self.from_comment_id is None and "from_comment_id" in self.model_fields_set:
            _dict['fromCommentId'] = None

        # set to None if from_vote_id (nullable) is None
        # and model_fields_set contains the field
        if self.from_vote_id is None and "from_vote_id" in self.model_fields_set:
            _dict['fromVoteId'] = None

        # set to None if from_user_name (nullable) is None
        # and model_fields_set contains the field
        if self.from_user_name is None and "from_user_name" in self.model_fields_set:
            _dict['fromUserName'] = None

        # set to None if from_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.from_user_id is None and "from_user_id" in self.model_fields_set:
            _dict['fromUserId'] = None

        # set to None if from_user_avatar_src (nullable) is None
        # and model_fields_set contains the field
        if self.from_user_avatar_src is None and "from_user_avatar_src" in self.model_fields_set:
            _dict['fromUserAvatarSrc'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserNotification from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "tenantId": obj.get("tenantId"),
            "userId": obj.get("userId"),
            "anonUserId": obj.get("anonUserId"),
            "urlId": obj.get("urlId"),
            "url": obj.get("url"),
            "pageTitle": obj.get("pageTitle"),
            "relatedObjectType": obj.get("relatedObjectType"),
            "relatedObjectId": obj.get("relatedObjectId"),
            "viewed": obj.get("viewed"),
            "isUnreadMessage": obj.get("isUnreadMessage"),
            "sent": obj.get("sent"),
            "createdAt": obj.get("createdAt"),
            "type": obj.get("type"),
            "fromCommentId": obj.get("fromCommentId"),
            "fromVoteId": obj.get("fromVoteId"),
            "fromUserName": obj.get("fromUserName"),
            "fromUserId": obj.get("fromUserId"),
            "fromUserAvatarSrc": obj.get("fromUserAvatarSrc"),
            "optedOut": obj.get("optedOut")
        })
        return _obj


