# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from client.models.custom_config_parameters import CustomConfigParameters
from client.models.imported_api_status_failed import ImportedAPIStatusFAILED
from typing import Optional, Set
from typing_extensions import Self

class APIError(BaseModel):
    """
    APIError
    """ # noqa: E501
    status: ImportedAPIStatusFAILED
    reason: StrictStr
    code: StrictStr
    secondary_code: Optional[StrictStr] = Field(default=None, alias="secondaryCode")
    banned_until: Optional[StrictInt] = Field(default=None, alias="bannedUntil")
    max_character_length: Optional[StrictInt] = Field(default=None, alias="maxCharacterLength")
    translated_error: Optional[StrictStr] = Field(default=None, alias="translatedError")
    custom_config: Optional[CustomConfigParameters] = Field(default=None, alias="customConfig")
    __properties: ClassVar[List[str]] = ["status", "reason", "code", "secondaryCode", "bannedUntil", "maxCharacterLength", "translatedError", "customConfig"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIError from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of custom_config
        if self.custom_config:
            _dict['customConfig'] = self.custom_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIError from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "reason": obj.get("reason"),
            "code": obj.get("code"),
            "secondaryCode": obj.get("secondaryCode"),
            "bannedUntil": obj.get("bannedUntil"),
            "maxCharacterLength": obj.get("maxCharacterLength"),
            "translatedError": obj.get("translatedError"),
            "customConfig": CustomConfigParameters.from_dict(obj["customConfig"]) if obj.get("customConfig") is not None else None
        })
        return _obj


