# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from client.models.banned_user_match import BannedUserMatch
from typing import Optional, Set
from typing_extensions import Self

class APIBannedUserWithMultiMatchInfo(BaseModel):
    """
    APIBannedUserWithMultiMatchInfo
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    ban_type: StrictStr = Field(alias="banType")
    email: Optional[StrictStr] = None
    ip_hash: Optional[StrictStr] = Field(default=None, alias="ipHash")
    banned_until: Optional[datetime] = Field(alias="bannedUntil")
    has_email_wildcard: StrictBool = Field(alias="hasEmailWildcard")
    ban_reason: Optional[StrictStr] = Field(default=None, alias="banReason")
    matches: List[BannedUserMatch]
    __properties: ClassVar[List[str]] = ["_id", "userId", "banType", "email", "ipHash", "bannedUntil", "hasEmailWildcard", "banReason", "matches"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIBannedUserWithMultiMatchInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in matches (list)
        _items = []
        if self.matches:
            for _item_matches in self.matches:
                if _item_matches:
                    _items.append(_item_matches.to_dict())
            _dict['matches'] = _items
        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['userId'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if ip_hash (nullable) is None
        # and model_fields_set contains the field
        if self.ip_hash is None and "ip_hash" in self.model_fields_set:
            _dict['ipHash'] = None

        # set to None if banned_until (nullable) is None
        # and model_fields_set contains the field
        if self.banned_until is None and "banned_until" in self.model_fields_set:
            _dict['bannedUntil'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIBannedUserWithMultiMatchInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "userId": obj.get("userId"),
            "banType": obj.get("banType"),
            "email": obj.get("email"),
            "ipHash": obj.get("ipHash"),
            "bannedUntil": obj.get("bannedUntil"),
            "hasEmailWildcard": obj.get("hasEmailWildcard"),
            "banReason": obj.get("banReason"),
            "matches": [BannedUserMatch.from_dict(_item) for _item in obj["matches"]] if obj.get("matches") is not None else None
        })
        return _obj


