# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from client.models.imported_site_type import ImportedSiteType
from typing import Optional, Set
from typing_extensions import Self

class APIDomainConfiguration(BaseModel):
    """
    APIDomainConfiguration
    """ # noqa: E501
    id: StrictStr
    domain: StrictStr
    email_from_name: Optional[StrictStr] = Field(default=None, alias="emailFromName")
    email_from_email: Optional[StrictStr] = Field(default=None, alias="emailFromEmail")
    email_headers: Optional[Dict[str, StrictStr]] = Field(default=None, description="Construct a type with a set of properties K of type T", alias="emailHeaders")
    wp_sync_token: Optional[StrictStr] = Field(default=None, alias="wpSyncToken")
    wp_synced: Optional[StrictBool] = Field(default=None, alias="wpSynced")
    wp_url: Optional[StrictStr] = Field(default=None, alias="wpURL")
    created_at: datetime = Field(alias="createdAt")
    auto_added_date: Optional[datetime] = Field(default=None, alias="autoAddedDate")
    site_type: Optional[ImportedSiteType] = Field(default=None, alias="siteType")
    logo_src: Optional[StrictStr] = Field(default=None, alias="logoSrc")
    logo_src100px: Optional[StrictStr] = Field(default=None, alias="logoSrc100px")
    footer_unsubscribe_url: Optional[StrictStr] = Field(default=None, alias="footerUnsubscribeURL")
    disable_unsubscribe_links: Optional[StrictBool] = Field(default=None, alias="disableUnsubscribeLinks")
    __properties: ClassVar[List[str]] = ["id", "domain", "emailFromName", "emailFromEmail", "emailHeaders", "wpSyncToken", "wpSynced", "wpURL", "createdAt", "autoAddedDate", "siteType", "logoSrc", "logoSrc100px", "footerUnsubscribeURL", "disableUnsubscribeLinks"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIDomainConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if email_from_name (nullable) is None
        # and model_fields_set contains the field
        if self.email_from_name is None and "email_from_name" in self.model_fields_set:
            _dict['emailFromName'] = None

        # set to None if email_from_email (nullable) is None
        # and model_fields_set contains the field
        if self.email_from_email is None and "email_from_email" in self.model_fields_set:
            _dict['emailFromEmail'] = None

        # set to None if wp_sync_token (nullable) is None
        # and model_fields_set contains the field
        if self.wp_sync_token is None and "wp_sync_token" in self.model_fields_set:
            _dict['wpSyncToken'] = None

        # set to None if wp_url (nullable) is None
        # and model_fields_set contains the field
        if self.wp_url is None and "wp_url" in self.model_fields_set:
            _dict['wpURL'] = None

        # set to None if logo_src (nullable) is None
        # and model_fields_set contains the field
        if self.logo_src is None and "logo_src" in self.model_fields_set:
            _dict['logoSrc'] = None

        # set to None if logo_src100px (nullable) is None
        # and model_fields_set contains the field
        if self.logo_src100px is None and "logo_src100px" in self.model_fields_set:
            _dict['logoSrc100px'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIDomainConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "domain": obj.get("domain"),
            "emailFromName": obj.get("emailFromName"),
            "emailFromEmail": obj.get("emailFromEmail"),
            "emailHeaders": obj.get("emailHeaders"),
            "wpSyncToken": obj.get("wpSyncToken"),
            "wpSynced": obj.get("wpSynced"),
            "wpURL": obj.get("wpURL"),
            "createdAt": obj.get("createdAt"),
            "autoAddedDate": obj.get("autoAddedDate"),
            "siteType": obj.get("siteType"),
            "logoSrc": obj.get("logoSrc"),
            "logoSrc100px": obj.get("logoSrc100px"),
            "footerUnsubscribeURL": obj.get("footerUnsubscribeURL"),
            "disableUnsubscribeLinks": obj.get("disableUnsubscribeLinks")
        })
        return _obj


