# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from client.models.comment_user_hash_tag_info import CommentUserHashTagInfo
from client.models.comment_user_mention_info import CommentUserMentionInfo
from client.models.record_string_string_or_number_value import RecordStringStringOrNumberValue
from typing import Optional, Set
from typing_extensions import Self

class CreateCommentParams(BaseModel):
    """
    CreateCommentParams
    """ # noqa: E501
    var_date: Optional[StrictInt] = Field(default=None, alias="date")
    local_date_string: Optional[StrictStr] = Field(default=None, alias="localDateString")
    local_date_hours: Optional[StrictInt] = Field(default=None, alias="localDateHours")
    commenter_name: StrictStr = Field(alias="commenterName")
    commenter_email: Optional[StrictStr] = Field(default=None, alias="commenterEmail")
    commenter_link: Optional[StrictStr] = Field(default=None, alias="commenterLink")
    comment: StrictStr
    product_id: Optional[StrictInt] = Field(default=None, alias="productId")
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    avatar_src: Optional[StrictStr] = Field(default=None, alias="avatarSrc")
    parent_id: Optional[StrictStr] = Field(default=None, alias="parentId")
    mentions: Optional[List[CommentUserMentionInfo]] = None
    hash_tags: Optional[List[CommentUserHashTagInfo]] = Field(default=None, alias="hashTags")
    page_title: Optional[StrictStr] = Field(default=None, alias="pageTitle")
    is_from_my_account_page: Optional[StrictBool] = Field(default=None, alias="isFromMyAccountPage")
    url: StrictStr
    url_id: StrictStr = Field(alias="urlId")
    meta: Optional[Dict[str, Any]] = None
    moderation_group_ids: Optional[List[StrictStr]] = Field(default=None, alias="moderationGroupIds")
    rating: Optional[Union[StrictFloat, StrictInt]] = None
    from_offline_restore: Optional[StrictBool] = Field(default=None, alias="fromOfflineRestore")
    autoplay_delay_ms: Optional[StrictInt] = Field(default=None, alias="autoplayDelayMS")
    feedback_ids: Optional[List[StrictStr]] = Field(default=None, alias="feedbackIds")
    question_values: Optional[Dict[str, RecordStringStringOrNumberValue]] = Field(default=None, description="Construct a type with a set of properties K of type T", alias="questionValues")
    approved: Optional[StrictBool] = None
    domain: Optional[StrictStr] = None
    ip: Optional[StrictStr] = None
    is_pinned: Optional[StrictBool] = Field(default=None, alias="isPinned")
    locale: StrictStr = Field(description="Example: en_us")
    reviewed: Optional[StrictBool] = None
    verified: Optional[StrictBool] = None
    votes: Optional[StrictInt] = None
    votes_down: Optional[StrictInt] = Field(default=None, alias="votesDown")
    votes_up: Optional[StrictInt] = Field(default=None, alias="votesUp")
    __properties: ClassVar[List[str]] = ["date", "localDateString", "localDateHours", "commenterName", "commenterEmail", "commenterLink", "comment", "productId", "userId", "avatarSrc", "parentId", "mentions", "hashTags", "pageTitle", "isFromMyAccountPage", "url", "urlId", "meta", "moderationGroupIds", "rating", "fromOfflineRestore", "autoplayDelayMS", "feedbackIds", "questionValues", "approved", "domain", "ip", "isPinned", "locale", "reviewed", "verified", "votes", "votesDown", "votesUp"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCommentParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in mentions (list)
        _items = []
        if self.mentions:
            for _item_mentions in self.mentions:
                if _item_mentions:
                    _items.append(_item_mentions.to_dict())
            _dict['mentions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in hash_tags (list)
        _items = []
        if self.hash_tags:
            for _item_hash_tags in self.hash_tags:
                if _item_hash_tags:
                    _items.append(_item_hash_tags.to_dict())
            _dict['hashTags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in question_values (dict)
        _field_dict = {}
        if self.question_values:
            for _key_question_values in self.question_values:
                if self.question_values[_key_question_values]:
                    _field_dict[_key_question_values] = self.question_values[_key_question_values].to_dict()
            _dict['questionValues'] = _field_dict
        # set to None if commenter_email (nullable) is None
        # and model_fields_set contains the field
        if self.commenter_email is None and "commenter_email" in self.model_fields_set:
            _dict['commenterEmail'] = None

        # set to None if commenter_link (nullable) is None
        # and model_fields_set contains the field
        if self.commenter_link is None and "commenter_link" in self.model_fields_set:
            _dict['commenterLink'] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['userId'] = None

        # set to None if avatar_src (nullable) is None
        # and model_fields_set contains the field
        if self.avatar_src is None and "avatar_src" in self.model_fields_set:
            _dict['avatarSrc'] = None

        # set to None if parent_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_id is None and "parent_id" in self.model_fields_set:
            _dict['parentId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCommentParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "localDateString": obj.get("localDateString"),
            "localDateHours": obj.get("localDateHours"),
            "commenterName": obj.get("commenterName"),
            "commenterEmail": obj.get("commenterEmail"),
            "commenterLink": obj.get("commenterLink"),
            "comment": obj.get("comment"),
            "productId": obj.get("productId"),
            "userId": obj.get("userId"),
            "avatarSrc": obj.get("avatarSrc"),
            "parentId": obj.get("parentId"),
            "mentions": [CommentUserMentionInfo.from_dict(_item) for _item in obj["mentions"]] if obj.get("mentions") is not None else None,
            "hashTags": [CommentUserHashTagInfo.from_dict(_item) for _item in obj["hashTags"]] if obj.get("hashTags") is not None else None,
            "pageTitle": obj.get("pageTitle"),
            "isFromMyAccountPage": obj.get("isFromMyAccountPage"),
            "url": obj.get("url"),
            "urlId": obj.get("urlId"),
            "meta": obj.get("meta"),
            "moderationGroupIds": obj.get("moderationGroupIds"),
            "rating": obj.get("rating"),
            "fromOfflineRestore": obj.get("fromOfflineRestore"),
            "autoplayDelayMS": obj.get("autoplayDelayMS"),
            "feedbackIds": obj.get("feedbackIds"),
            "questionValues": dict(
                (_k, RecordStringStringOrNumberValue.from_dict(_v))
                for _k, _v in obj["questionValues"].items()
            )
            if obj.get("questionValues") is not None
            else None,
            "approved": obj.get("approved"),
            "domain": obj.get("domain"),
            "ip": obj.get("ip"),
            "isPinned": obj.get("isPinned"),
            "locale": obj.get("locale"),
            "reviewed": obj.get("reviewed"),
            "verified": obj.get("verified"),
            "votes": obj.get("votes"),
            "votesDown": obj.get("votesDown"),
            "votesUp": obj.get("votesUp")
        })
        return _obj


