# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CreateTenantPackageBody(BaseModel):
    """
    CreateTenantPackageBody
    """ # noqa: E501
    name: StrictStr
    monthly_cost_usd: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="monthlyCostUSD")
    yearly_cost_usd: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="yearlyCostUSD")
    monthly_stripe_plan_id: Optional[StrictStr] = Field(default=None, alias="monthlyStripePlanId")
    yearly_stripe_plan_id: Optional[StrictStr] = Field(default=None, alias="yearlyStripePlanId")
    max_monthly_page_loads: Union[StrictFloat, StrictInt] = Field(alias="maxMonthlyPageLoads")
    max_monthly_api_credits: Union[StrictFloat, StrictInt] = Field(alias="maxMonthlyAPICredits")
    max_monthly_small_widgets_credits: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maxMonthlySmallWidgetsCredits")
    max_monthly_comments: Union[StrictFloat, StrictInt] = Field(alias="maxMonthlyComments")
    max_concurrent_users: Union[StrictFloat, StrictInt] = Field(alias="maxConcurrentUsers")
    max_tenant_users: Union[StrictFloat, StrictInt] = Field(alias="maxTenantUsers")
    max_sso_users: Union[StrictFloat, StrictInt] = Field(alias="maxSSOUsers")
    max_moderators: Union[StrictFloat, StrictInt] = Field(alias="maxModerators")
    max_domains: Union[StrictFloat, StrictInt] = Field(alias="maxDomains")
    max_white_labeled_tenants: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maxWhiteLabeledTenants")
    max_monthly_event_log_requests: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maxMonthlyEventLogRequests")
    has_white_labeling: Optional[StrictBool] = Field(default=None, alias="hasWhiteLabeling")
    has_debranding: StrictBool = Field(alias="hasDebranding")
    has_llm_spam_detection: Optional[StrictBool] = Field(default=None, alias="hasLLMSpamDetection")
    for_who_text: StrictStr = Field(alias="forWhoText")
    feature_taglines: List[StrictStr] = Field(alias="featureTaglines")
    has_auditing: Optional[StrictBool] = Field(default=None, alias="hasAuditing")
    has_flex_pricing: StrictBool = Field(alias="hasFlexPricing")
    enable_saml: Optional[StrictBool] = Field(default=None, alias="enableSAML")
    flex_page_load_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexPageLoadCostCents")
    flex_page_load_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexPageLoadUnit")
    flex_comment_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexCommentCostCents")
    flex_comment_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexCommentUnit")
    flex_sso_user_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexSSOUserCostCents")
    flex_sso_user_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexSSOUserUnit")
    flex_api_credit_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexAPICreditCostCents")
    flex_api_credit_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexAPICreditUnit")
    flex_small_widgets_credit_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexSmallWidgetsCreditCostCents")
    flex_small_widgets_credit_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexSmallWidgetsCreditUnit")
    flex_moderator_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexModeratorCostCents")
    flex_moderator_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexModeratorUnit")
    flex_admin_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexAdminCostCents")
    flex_admin_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexAdminUnit")
    flex_domain_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexDomainCostCents")
    flex_domain_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexDomainUnit")
    flex_chat_gpt_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexChatGPTCostCents")
    flex_chat_gpt_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexChatGPTUnit")
    flex_minimum_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexMinimumCostCents")
    flex_managed_tenant_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexManagedTenantCostCents")
    flex_sso_admin_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexSSOAdminCostCents")
    flex_sso_admin_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexSSOAdminUnit")
    flex_sso_moderator_cost_cents: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexSSOModeratorCostCents")
    flex_sso_moderator_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flexSSOModeratorUnit")
    __properties: ClassVar[List[str]] = ["name", "monthlyCostUSD", "yearlyCostUSD", "monthlyStripePlanId", "yearlyStripePlanId", "maxMonthlyPageLoads", "maxMonthlyAPICredits", "maxMonthlySmallWidgetsCredits", "maxMonthlyComments", "maxConcurrentUsers", "maxTenantUsers", "maxSSOUsers", "maxModerators", "maxDomains", "maxWhiteLabeledTenants", "maxMonthlyEventLogRequests", "hasWhiteLabeling", "hasDebranding", "hasLLMSpamDetection", "forWhoText", "featureTaglines", "hasAuditing", "hasFlexPricing", "enableSAML", "flexPageLoadCostCents", "flexPageLoadUnit", "flexCommentCostCents", "flexCommentUnit", "flexSSOUserCostCents", "flexSSOUserUnit", "flexAPICreditCostCents", "flexAPICreditUnit", "flexSmallWidgetsCreditCostCents", "flexSmallWidgetsCreditUnit", "flexModeratorCostCents", "flexModeratorUnit", "flexAdminCostCents", "flexAdminUnit", "flexDomainCostCents", "flexDomainUnit", "flexChatGPTCostCents", "flexChatGPTUnit", "flexMinimumCostCents", "flexManagedTenantCostCents", "flexSSOAdminCostCents", "flexSSOAdminUnit", "flexSSOModeratorCostCents", "flexSSOModeratorUnit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateTenantPackageBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if monthly_cost_usd (nullable) is None
        # and model_fields_set contains the field
        if self.monthly_cost_usd is None and "monthly_cost_usd" in self.model_fields_set:
            _dict['monthlyCostUSD'] = None

        # set to None if yearly_cost_usd (nullable) is None
        # and model_fields_set contains the field
        if self.yearly_cost_usd is None and "yearly_cost_usd" in self.model_fields_set:
            _dict['yearlyCostUSD'] = None

        # set to None if monthly_stripe_plan_id (nullable) is None
        # and model_fields_set contains the field
        if self.monthly_stripe_plan_id is None and "monthly_stripe_plan_id" in self.model_fields_set:
            _dict['monthlyStripePlanId'] = None

        # set to None if yearly_stripe_plan_id (nullable) is None
        # and model_fields_set contains the field
        if self.yearly_stripe_plan_id is None and "yearly_stripe_plan_id" in self.model_fields_set:
            _dict['yearlyStripePlanId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateTenantPackageBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "monthlyCostUSD": obj.get("monthlyCostUSD"),
            "yearlyCostUSD": obj.get("yearlyCostUSD"),
            "monthlyStripePlanId": obj.get("monthlyStripePlanId"),
            "yearlyStripePlanId": obj.get("yearlyStripePlanId"),
            "maxMonthlyPageLoads": obj.get("maxMonthlyPageLoads"),
            "maxMonthlyAPICredits": obj.get("maxMonthlyAPICredits"),
            "maxMonthlySmallWidgetsCredits": obj.get("maxMonthlySmallWidgetsCredits"),
            "maxMonthlyComments": obj.get("maxMonthlyComments"),
            "maxConcurrentUsers": obj.get("maxConcurrentUsers"),
            "maxTenantUsers": obj.get("maxTenantUsers"),
            "maxSSOUsers": obj.get("maxSSOUsers"),
            "maxModerators": obj.get("maxModerators"),
            "maxDomains": obj.get("maxDomains"),
            "maxWhiteLabeledTenants": obj.get("maxWhiteLabeledTenants"),
            "maxMonthlyEventLogRequests": obj.get("maxMonthlyEventLogRequests"),
            "hasWhiteLabeling": obj.get("hasWhiteLabeling"),
            "hasDebranding": obj.get("hasDebranding"),
            "hasLLMSpamDetection": obj.get("hasLLMSpamDetection"),
            "forWhoText": obj.get("forWhoText"),
            "featureTaglines": obj.get("featureTaglines"),
            "hasAuditing": obj.get("hasAuditing"),
            "hasFlexPricing": obj.get("hasFlexPricing"),
            "enableSAML": obj.get("enableSAML"),
            "flexPageLoadCostCents": obj.get("flexPageLoadCostCents"),
            "flexPageLoadUnit": obj.get("flexPageLoadUnit"),
            "flexCommentCostCents": obj.get("flexCommentCostCents"),
            "flexCommentUnit": obj.get("flexCommentUnit"),
            "flexSSOUserCostCents": obj.get("flexSSOUserCostCents"),
            "flexSSOUserUnit": obj.get("flexSSOUserUnit"),
            "flexAPICreditCostCents": obj.get("flexAPICreditCostCents"),
            "flexAPICreditUnit": obj.get("flexAPICreditUnit"),
            "flexSmallWidgetsCreditCostCents": obj.get("flexSmallWidgetsCreditCostCents"),
            "flexSmallWidgetsCreditUnit": obj.get("flexSmallWidgetsCreditUnit"),
            "flexModeratorCostCents": obj.get("flexModeratorCostCents"),
            "flexModeratorUnit": obj.get("flexModeratorUnit"),
            "flexAdminCostCents": obj.get("flexAdminCostCents"),
            "flexAdminUnit": obj.get("flexAdminUnit"),
            "flexDomainCostCents": obj.get("flexDomainCostCents"),
            "flexDomainUnit": obj.get("flexDomainUnit"),
            "flexChatGPTCostCents": obj.get("flexChatGPTCostCents"),
            "flexChatGPTUnit": obj.get("flexChatGPTUnit"),
            "flexMinimumCostCents": obj.get("flexMinimumCostCents"),
            "flexManagedTenantCostCents": obj.get("flexManagedTenantCostCents"),
            "flexSSOAdminCostCents": obj.get("flexSSOAdminCostCents"),
            "flexSSOAdminUnit": obj.get("flexSSOAdminUnit"),
            "flexSSOModeratorCostCents": obj.get("flexSSOModeratorCostCents"),
            "flexSSOModeratorUnit": obj.get("flexSSOModeratorUnit")
        })
        return _obj


