# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateEmailTemplateBody(BaseModel):
    """
    CreateEmailTemplateBody
    """ # noqa: E501
    email_template_id: StrictStr = Field(alias="emailTemplateId")
    display_name: StrictStr = Field(alias="displayName")
    ejs: StrictStr
    domain: Optional[StrictStr] = None
    translation_overrides_by_locale: Optional[Dict[str, Dict[str, StrictStr]]] = Field(default=None, description="Construct a type with a set of properties K of type T", alias="translationOverridesByLocale")
    test_data: Optional[Dict[str, Any]] = Field(default=None, description="Construct a type with a set of properties K of type T", alias="testData")
    __properties: ClassVar[List[str]] = ["emailTemplateId", "displayName", "ejs", "domain", "translationOverridesByLocale", "testData"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateEmailTemplateBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateEmailTemplateBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "emailTemplateId": obj.get("emailTemplateId"),
            "displayName": obj.get("displayName"),
            "ejs": obj.get("ejs"),
            "domain": obj.get("domain"),
            "translationOverridesByLocale": obj.get("translationOverridesByLocale"),
            "testData": obj.get("testData")
        })
        return _obj


