# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from client.models.api_status import APIStatus
from client.models.pending_comment_to_sync_outbound import PendingCommentToSyncOutbound
from typing import Optional, Set
from typing_extensions import Self

class GetPendingWebhookEventsResponse(BaseModel):
    """
    GetPendingWebhookEventsResponse
    """ # noqa: E501
    status: APIStatus
    pending_webhook_events: List[PendingCommentToSyncOutbound] = Field(alias="pendingWebhookEvents")
    __properties: ClassVar[List[str]] = ["status", "pendingWebhookEvents"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetPendingWebhookEventsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pending_webhook_events (list)
        _items = []
        if self.pending_webhook_events:
            for _item_pending_webhook_events in self.pending_webhook_events:
                if _item_pending_webhook_events:
                    _items.append(_item_pending_webhook_events.to_dict())
            _dict['pendingWebhookEvents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetPendingWebhookEventsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "pendingWebhookEvents": [PendingCommentToSyncOutbound.from_dict(_item) for _item in obj["pendingWebhookEvents"]] if obj.get("pendingWebhookEvents") is not None else None
        })
        return _obj


