# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HeaderAccountNotification(BaseModel):
    """
    HeaderAccountNotification
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    title: StrictStr
    message: StrictStr
    messages_by_locale: Optional[Dict[str, StrictStr]] = Field(description="Construct a type with a set of properties K of type T", alias="messagesByLocale")
    dates: Optional[Dict[str, StrictStr]] = Field(description="Construct a type with a set of properties K of type T")
    severity: StrictStr
    link_url: Optional[StrictStr] = Field(alias="linkUrl")
    link_text: Optional[StrictStr] = Field(alias="linkText")
    created_at: datetime = Field(alias="createdAt")
    __properties: ClassVar[List[str]] = ["_id", "title", "message", "messagesByLocale", "dates", "severity", "linkUrl", "linkText", "createdAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HeaderAccountNotification from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if messages_by_locale (nullable) is None
        # and model_fields_set contains the field
        if self.messages_by_locale is None and "messages_by_locale" in self.model_fields_set:
            _dict['messagesByLocale'] = None

        # set to None if dates (nullable) is None
        # and model_fields_set contains the field
        if self.dates is None and "dates" in self.model_fields_set:
            _dict['dates'] = None

        # set to None if link_url (nullable) is None
        # and model_fields_set contains the field
        if self.link_url is None and "link_url" in self.model_fields_set:
            _dict['linkUrl'] = None

        # set to None if link_text (nullable) is None
        # and model_fields_set contains the field
        if self.link_text is None and "link_text" in self.model_fields_set:
            _dict['linkText'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HeaderAccountNotification from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "title": obj.get("title"),
            "message": obj.get("message"),
            "messagesByLocale": obj.get("messagesByLocale"),
            "dates": obj.get("dates"),
            "severity": obj.get("severity"),
            "linkUrl": obj.get("linkUrl"),
            "linkText": obj.get("linkText"),
            "createdAt": obj.get("createdAt")
        })
        return _obj


