# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LiveEventType(str, Enum):
    """
    LiveEventType
    """

    """
    allowed enum values
    """
    UPDATE_MINUS_BADGES = 'update-badges'
    NOTIFICATION = 'notification'
    NOTIFICATION_MINUS_UPDATE = 'notification-update'
    P_MINUS_U = 'p-u'
    NEW_MINUS_VOTE = 'new-vote'
    DELETED_MINUS_VOTE = 'deleted-vote'
    NEW_MINUS_COMMENT = 'new-comment'
    UPDATED_MINUS_COMMENT = 'updated-comment'
    DELETED_MINUS_COMMENT = 'deleted-comment'
    CVC = 'cvc'
    NEW_MINUS_CONFIG = 'new-config'
    THREAD_MINUS_STATE_MINUS_CHANGE = 'thread-state-change'
    FR = 'fr'
    DFR = 'dfr'
    NEW_MINUS_FEED_MINUS_POST = 'new-feed-post'
    UPDATED_MINUS_FEED_MINUS_POST = 'updated-feed-post'
    DELETED_MINUS_FEED_MINUS_POST = 'deleted-feed-post'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LiveEventType from a JSON string"""
        return cls(json.loads(json_str))


