# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from client.models.f_comment import FComment
from typing import Optional, Set
from typing_extensions import Self

class PendingCommentToSyncOutbound(BaseModel):
    """
    PendingCommentToSyncOutbound
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    comment_id: StrictStr = Field(alias="commentId")
    comment: Optional[FComment] = None
    external_id: Optional[StrictStr] = Field(alias="externalId")
    created_at: datetime = Field(alias="createdAt")
    tenant_id: StrictStr = Field(alias="tenantId")
    attempt_count: Union[StrictFloat, StrictInt] = Field(alias="attemptCount")
    next_attempt_at: datetime = Field(alias="nextAttemptAt")
    event_type: Union[StrictFloat, StrictInt] = Field(alias="eventType")
    type: Union[StrictFloat, StrictInt]
    domain: StrictStr
    last_error: Dict[str, Any] = Field(alias="lastError")
    webhook_id: Optional[StrictStr] = Field(default=None, alias="webhookId")
    __properties: ClassVar[List[str]] = ["_id", "commentId", "comment", "externalId", "createdAt", "tenantId", "attemptCount", "nextAttemptAt", "eventType", "type", "domain", "lastError", "webhookId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PendingCommentToSyncOutbound from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of comment
        if self.comment:
            _dict['comment'] = self.comment.to_dict()
        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['externalId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PendingCommentToSyncOutbound from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "commentId": obj.get("commentId"),
            "comment": FComment.from_dict(obj["comment"]) if obj.get("comment") is not None else None,
            "externalId": obj.get("externalId"),
            "createdAt": obj.get("createdAt"),
            "tenantId": obj.get("tenantId"),
            "attemptCount": obj.get("attemptCount"),
            "nextAttemptAt": obj.get("nextAttemptAt"),
            "eventType": obj.get("eventType"),
            "type": obj.get("type"),
            "domain": obj.get("domain"),
            "lastError": obj.get("lastError"),
            "webhookId": obj.get("webhookId")
        })
        return _obj


