# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PickTenantAuditLogTenantAuditLogKeys(BaseModel):
    """
    From T, pick a set of properties whose keys are in the union K
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    url: Optional[StrictStr] = None
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    username: Optional[StrictStr] = None
    resource_name: StrictStr = Field(alias="resourceName")
    crud_type: StrictStr = Field(alias="crudType")
    var_from: Optional[StrictStr] = Field(default=None, alias="from")
    ip: Optional[StrictStr] = None
    when: Optional[datetime] = None
    description: Optional[StrictStr] = None
    server_start_date: Optional[datetime] = Field(default=None, alias="serverStartDate")
    object_details: Optional[Dict[str, Any]] = Field(default=None, description="Construct a type with a set of properties K of type T", alias="objectDetails")
    __properties: ClassVar[List[str]] = ["_id", "url", "userId", "username", "resourceName", "crudType", "from", "ip", "when", "description", "serverStartDate", "objectDetails"]

    @field_validator('crud_type')
    def crud_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['c', 'r', 'u', 'd', 'login']):
            raise ValueError("must be one of enum values ('c', 'r', 'u', 'd', 'login')")
        return value

    @field_validator('var_from')
    def var_from_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ui', 'api', 'cron']):
            raise ValueError("must be one of enum values ('ui', 'api', 'cron')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PickTenantAuditLogTenantAuditLogKeys from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PickTenantAuditLogTenantAuditLogKeys from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "url": obj.get("url"),
            "userId": obj.get("userId"),
            "username": obj.get("username"),
            "resourceName": obj.get("resourceName"),
            "crudType": obj.get("crudType"),
            "from": obj.get("from"),
            "ip": obj.get("ip"),
            "when": obj.get("when"),
            "description": obj.get("description"),
            "serverStartDate": obj.get("serverStartDate"),
            "objectDetails": obj.get("objectDetails")
        })
        return _obj


