# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from client.models.comment_user_badge_info import CommentUserBadgeInfo
from typing import Optional, Set
from typing_extensions import Self

class PublicComment(BaseModel):
    """
    PublicComment
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    commenter_name: StrictStr = Field(alias="commenterName")
    commenter_link: Optional[StrictStr] = Field(default=None, alias="commenterLink")
    comment_html: StrictStr = Field(alias="commentHTML")
    parent_id: Optional[StrictStr] = Field(default=None, alias="parentId")
    var_date: Optional[datetime] = Field(alias="date")
    votes: Optional[StrictInt] = None
    votes_up: Optional[StrictInt] = Field(default=None, alias="votesUp")
    votes_down: Optional[StrictInt] = Field(default=None, alias="votesDown")
    verified: StrictBool
    avatar_src: Optional[StrictStr] = Field(default=None, alias="avatarSrc")
    has_images: Optional[StrictBool] = Field(default=None, alias="hasImages")
    is_by_admin: Optional[StrictBool] = Field(default=None, alias="isByAdmin")
    is_by_moderator: Optional[StrictBool] = Field(default=None, alias="isByModerator")
    is_pinned: Optional[StrictBool] = Field(default=None, alias="isPinned")
    is_locked: Optional[StrictBool] = Field(default=None, alias="isLocked")
    display_label: Optional[StrictStr] = Field(default=None, alias="displayLabel")
    rating: Optional[Union[StrictFloat, StrictInt]] = None
    badges: Optional[List[CommentUserBadgeInfo]] = None
    view_count: Optional[StrictInt] = Field(default=None, alias="viewCount")
    is_deleted: Optional[StrictBool] = Field(default=None, alias="isDeleted")
    is_deleted_user: Optional[StrictBool] = Field(default=None, alias="isDeletedUser")
    is_spam: Optional[StrictBool] = Field(default=None, alias="isSpam")
    anon_user_id: Optional[StrictStr] = Field(default=None, alias="anonUserId")
    feedback_ids: Optional[List[StrictStr]] = Field(default=None, alias="feedbackIds")
    requires_verification: Optional[StrictBool] = Field(default=None, alias="requiresVerification")
    edit_key: Optional[StrictStr] = Field(default=None, alias="editKey")
    approved: Optional[StrictBool] = None
    is_unread: Optional[StrictBool] = Field(default=None, alias="isUnread")
    my_vote_id: Optional[StrictStr] = Field(default=None, alias="myVoteId")
    is_voted_down: Optional[StrictBool] = Field(default=None, alias="isVotedDown")
    is_voted_up: Optional[StrictBool] = Field(default=None, alias="isVotedUp")
    has_children: Optional[StrictBool] = Field(default=None, description="This is always set when asTree=true", alias="hasChildren")
    nested_children_count: Optional[StrictInt] = Field(default=None, description="The total nested child count included in this response (may be more available w/ pagination) Only set with asTree=true, otherwise this will be null.", alias="nestedChildrenCount")
    child_count: Optional[StrictInt] = Field(default=None, description="You must ask the API to count children (with asTree=true&countChildren=true), otherwise this will be null. This will be the complete direct child count, whereas children may only contain a subset based on pagination.", alias="childCount")
    children: Optional[List[PublicComment]] = None
    is_flagged: Optional[StrictBool] = Field(default=None, alias="isFlagged")
    is_blocked: Optional[StrictBool] = Field(default=None, alias="isBlocked")
    __properties: ClassVar[List[str]] = ["_id", "userId", "commenterName", "commenterLink", "commentHTML", "parentId", "date", "votes", "votesUp", "votesDown", "verified", "avatarSrc", "hasImages", "isByAdmin", "isByModerator", "isPinned", "isLocked", "displayLabel", "rating", "badges", "viewCount", "isDeleted", "isDeletedUser", "isSpam", "anonUserId", "feedbackIds", "requiresVerification", "editKey", "approved", "isUnread", "myVoteId", "isVotedDown", "isVotedUp", "hasChildren", "nestedChildrenCount", "childCount", "children", "isFlagged", "isBlocked"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicComment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in badges (list)
        _items = []
        if self.badges:
            for _item_badges in self.badges:
                if _item_badges:
                    _items.append(_item_badges.to_dict())
            _dict['badges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict['children'] = _items
        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['userId'] = None

        # set to None if commenter_link (nullable) is None
        # and model_fields_set contains the field
        if self.commenter_link is None and "commenter_link" in self.model_fields_set:
            _dict['commenterLink'] = None

        # set to None if parent_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_id is None and "parent_id" in self.model_fields_set:
            _dict['parentId'] = None

        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        # set to None if votes (nullable) is None
        # and model_fields_set contains the field
        if self.votes is None and "votes" in self.model_fields_set:
            _dict['votes'] = None

        # set to None if votes_up (nullable) is None
        # and model_fields_set contains the field
        if self.votes_up is None and "votes_up" in self.model_fields_set:
            _dict['votesUp'] = None

        # set to None if votes_down (nullable) is None
        # and model_fields_set contains the field
        if self.votes_down is None and "votes_down" in self.model_fields_set:
            _dict['votesDown'] = None

        # set to None if avatar_src (nullable) is None
        # and model_fields_set contains the field
        if self.avatar_src is None and "avatar_src" in self.model_fields_set:
            _dict['avatarSrc'] = None

        # set to None if is_pinned (nullable) is None
        # and model_fields_set contains the field
        if self.is_pinned is None and "is_pinned" in self.model_fields_set:
            _dict['isPinned'] = None

        # set to None if is_locked (nullable) is None
        # and model_fields_set contains the field
        if self.is_locked is None and "is_locked" in self.model_fields_set:
            _dict['isLocked'] = None

        # set to None if display_label (nullable) is None
        # and model_fields_set contains the field
        if self.display_label is None and "display_label" in self.model_fields_set:
            _dict['displayLabel'] = None

        # set to None if rating (nullable) is None
        # and model_fields_set contains the field
        if self.rating is None and "rating" in self.model_fields_set:
            _dict['rating'] = None

        # set to None if badges (nullable) is None
        # and model_fields_set contains the field
        if self.badges is None and "badges" in self.model_fields_set:
            _dict['badges'] = None

        # set to None if view_count (nullable) is None
        # and model_fields_set contains the field
        if self.view_count is None and "view_count" in self.model_fields_set:
            _dict['viewCount'] = None

        # set to None if anon_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.anon_user_id is None and "anon_user_id" in self.model_fields_set:
            _dict['anonUserId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicComment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "userId": obj.get("userId"),
            "commenterName": obj.get("commenterName"),
            "commenterLink": obj.get("commenterLink"),
            "commentHTML": obj.get("commentHTML"),
            "parentId": obj.get("parentId"),
            "date": obj.get("date"),
            "votes": obj.get("votes"),
            "votesUp": obj.get("votesUp"),
            "votesDown": obj.get("votesDown"),
            "verified": obj.get("verified"),
            "avatarSrc": obj.get("avatarSrc"),
            "hasImages": obj.get("hasImages"),
            "isByAdmin": obj.get("isByAdmin"),
            "isByModerator": obj.get("isByModerator"),
            "isPinned": obj.get("isPinned"),
            "isLocked": obj.get("isLocked"),
            "displayLabel": obj.get("displayLabel"),
            "rating": obj.get("rating"),
            "badges": [CommentUserBadgeInfo.from_dict(_item) for _item in obj["badges"]] if obj.get("badges") is not None else None,
            "viewCount": obj.get("viewCount"),
            "isDeleted": obj.get("isDeleted"),
            "isDeletedUser": obj.get("isDeletedUser"),
            "isSpam": obj.get("isSpam"),
            "anonUserId": obj.get("anonUserId"),
            "feedbackIds": obj.get("feedbackIds"),
            "requiresVerification": obj.get("requiresVerification"),
            "editKey": obj.get("editKey"),
            "approved": obj.get("approved"),
            "isUnread": obj.get("isUnread"),
            "myVoteId": obj.get("myVoteId"),
            "isVotedDown": obj.get("isVotedDown"),
            "isVotedUp": obj.get("isVotedUp"),
            "hasChildren": obj.get("hasChildren"),
            "nestedChildrenCount": obj.get("nestedChildrenCount"),
            "childCount": obj.get("childCount"),
            "children": [PublicComment.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "isFlagged": obj.get("isFlagged"),
            "isBlocked": obj.get("isBlocked")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
PublicComment.model_rebuild(raise_errors=False)

