# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from client.models.question_config_custom_options_inner import QuestionConfigCustomOptionsInner
from typing import Optional, Set
from typing_extensions import Self

class QuestionConfig(BaseModel):
    """
    QuestionConfig
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    tenant_id: StrictStr = Field(alias="tenantId")
    name: StrictStr
    question: StrictStr
    summary_label: Optional[StrictStr] = Field(default=None, alias="summaryLabel")
    help_text: StrictStr = Field(alias="helpText")
    created_at: datetime = Field(alias="createdAt")
    created_by: StrictStr = Field(alias="createdBy")
    used_count: Union[StrictFloat, StrictInt] = Field(alias="usedCount")
    last_used: datetime = Field(alias="lastUsed")
    type: StrictStr
    num_stars: Union[StrictFloat, StrictInt] = Field(alias="numStars")
    min: Union[StrictFloat, StrictInt]
    max: Union[StrictFloat, StrictInt]
    default_value: Union[StrictFloat, StrictInt] = Field(alias="defaultValue")
    label_negative: StrictStr = Field(alias="labelNegative")
    label_positive: StrictStr = Field(alias="labelPositive")
    custom_options: List[QuestionConfigCustomOptionsInner] = Field(alias="customOptions")
    sub_question_ids: List[StrictStr] = Field(alias="subQuestionIds")
    always_show_sub_questions: StrictBool = Field(alias="alwaysShowSubQuestions")
    reporting_order: Union[StrictFloat, StrictInt] = Field(alias="reportingOrder")
    __properties: ClassVar[List[str]] = ["_id", "tenantId", "name", "question", "summaryLabel", "helpText", "createdAt", "createdBy", "usedCount", "lastUsed", "type", "numStars", "min", "max", "defaultValue", "labelNegative", "labelPositive", "customOptions", "subQuestionIds", "alwaysShowSubQuestions", "reportingOrder"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuestionConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom_options (list)
        _items = []
        if self.custom_options:
            for _item_custom_options in self.custom_options:
                if _item_custom_options:
                    _items.append(_item_custom_options.to_dict())
            _dict['customOptions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuestionConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "tenantId": obj.get("tenantId"),
            "name": obj.get("name"),
            "question": obj.get("question"),
            "summaryLabel": obj.get("summaryLabel"),
            "helpText": obj.get("helpText"),
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "usedCount": obj.get("usedCount"),
            "lastUsed": obj.get("lastUsed"),
            "type": obj.get("type"),
            "numStars": obj.get("numStars"),
            "min": obj.get("min"),
            "max": obj.get("max"),
            "defaultValue": obj.get("defaultValue"),
            "labelNegative": obj.get("labelNegative"),
            "labelPositive": obj.get("labelPositive"),
            "customOptions": [QuestionConfigCustomOptionsInner.from_dict(_item) for _item in obj["customOptions"]] if obj.get("customOptions") is not None else None,
            "subQuestionIds": obj.get("subQuestionIds"),
            "alwaysShowSubQuestions": obj.get("alwaysShowSubQuestions"),
            "reportingOrder": obj.get("reportingOrder")
        })
        return _obj


