# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from client.models.api_domain_configuration import APIDomainConfiguration
from client.models.billing_info import BillingInfo
from typing import Optional, Set
from typing_extensions import Self

class UpdateTenantBody(BaseModel):
    """
    UpdateTenantBody
    """ # noqa: E501
    name: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    sign_up_date: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="signUpDate")
    package_id: Optional[StrictStr] = Field(default=None, alias="packageId")
    payment_frequency: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="paymentFrequency")
    billing_info_valid: Optional[StrictBool] = Field(default=None, alias="billingInfoValid")
    billing_handled_externally: Optional[StrictBool] = Field(default=None, alias="billingHandledExternally")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    is_setup: Optional[StrictBool] = Field(default=None, alias="isSetup")
    domain_configuration: Optional[List[APIDomainConfiguration]] = Field(default=None, alias="domainConfiguration")
    billing_info: Optional[BillingInfo] = Field(default=None, alias="billingInfo")
    stripe_customer_id: Optional[StrictStr] = Field(default=None, alias="stripeCustomerId")
    stripe_subscription_id: Optional[StrictStr] = Field(default=None, alias="stripeSubscriptionId")
    stripe_plan_id: Optional[StrictStr] = Field(default=None, alias="stripePlanId")
    enable_profanity_filter: Optional[StrictBool] = Field(default=None, alias="enableProfanityFilter")
    enable_spam_filter: Optional[StrictBool] = Field(default=None, alias="enableSpamFilter")
    remove_unverified_comments: Optional[StrictBool] = Field(default=None, alias="removeUnverifiedComments")
    unverified_comments_tt_lms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="unverifiedCommentsTTLms")
    comments_require_approval: Optional[StrictBool] = Field(default=None, alias="commentsRequireApproval")
    auto_approve_comment_on_verification: Optional[StrictBool] = Field(default=None, alias="autoApproveCommentOnVerification")
    send_profane_to_spam: Optional[StrictBool] = Field(default=None, alias="sendProfaneToSpam")
    de_anon_ip_addr: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="deAnonIpAddr")
    meta: Optional[Dict[str, StrictStr]] = Field(default=None, description="Construct a type with a set of properties K of type T")
    managed_by_tenant_id: Optional[StrictStr] = Field(default=None, alias="managedByTenantId")
    __properties: ClassVar[List[str]] = ["name", "email", "signUpDate", "packageId", "paymentFrequency", "billingInfoValid", "billingHandledExternally", "createdBy", "isSetup", "domainConfiguration", "billingInfo", "stripeCustomerId", "stripeSubscriptionId", "stripePlanId", "enableProfanityFilter", "enableSpamFilter", "removeUnverifiedComments", "unverifiedCommentsTTLms", "commentsRequireApproval", "autoApproveCommentOnVerification", "sendProfaneToSpam", "deAnonIpAddr", "meta", "managedByTenantId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateTenantBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in domain_configuration (list)
        _items = []
        if self.domain_configuration:
            for _item_domain_configuration in self.domain_configuration:
                if _item_domain_configuration:
                    _items.append(_item_domain_configuration.to_dict())
            _dict['domainConfiguration'] = _items
        # override the default output from pydantic by calling `to_dict()` of billing_info
        if self.billing_info:
            _dict['billingInfo'] = self.billing_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateTenantBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "email": obj.get("email"),
            "signUpDate": obj.get("signUpDate"),
            "packageId": obj.get("packageId"),
            "paymentFrequency": obj.get("paymentFrequency"),
            "billingInfoValid": obj.get("billingInfoValid"),
            "billingHandledExternally": obj.get("billingHandledExternally"),
            "createdBy": obj.get("createdBy"),
            "isSetup": obj.get("isSetup"),
            "domainConfiguration": [APIDomainConfiguration.from_dict(_item) for _item in obj["domainConfiguration"]] if obj.get("domainConfiguration") is not None else None,
            "billingInfo": BillingInfo.from_dict(obj["billingInfo"]) if obj.get("billingInfo") is not None else None,
            "stripeCustomerId": obj.get("stripeCustomerId"),
            "stripeSubscriptionId": obj.get("stripeSubscriptionId"),
            "stripePlanId": obj.get("stripePlanId"),
            "enableProfanityFilter": obj.get("enableProfanityFilter"),
            "enableSpamFilter": obj.get("enableSpamFilter"),
            "removeUnverifiedComments": obj.get("removeUnverifiedComments"),
            "unverifiedCommentsTTLms": obj.get("unverifiedCommentsTTLms"),
            "commentsRequireApproval": obj.get("commentsRequireApproval"),
            "autoApproveCommentOnVerification": obj.get("autoApproveCommentOnVerification"),
            "sendProfaneToSpam": obj.get("sendProfaneToSpam"),
            "deAnonIpAddr": obj.get("deAnonIpAddr"),
            "meta": obj.get("meta"),
            "managedByTenantId": obj.get("managedByTenantId")
        })
        return _obj


