# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateAPISSOUserData(BaseModel):
    """
    UpdateAPISSOUserData
    """ # noqa: E501
    group_ids: Optional[List[StrictStr]] = Field(default=None, alias="groupIds")
    has_blocked_users: Optional[StrictBool] = Field(default=None, alias="hasBlockedUsers")
    is_profile_dm_disabled: Optional[StrictBool] = Field(default=None, alias="isProfileDMDisabled")
    is_profile_comments_private: Optional[StrictBool] = Field(default=None, alias="isProfileCommentsPrivate")
    is_profile_activity_private: Optional[StrictBool] = Field(default=None, alias="isProfileActivityPrivate")
    is_comment_moderator_admin: Optional[StrictBool] = Field(default=None, alias="isCommentModeratorAdmin")
    is_admin_admin: Optional[StrictBool] = Field(default=None, alias="isAdminAdmin")
    is_account_owner: Optional[StrictBool] = Field(default=None, alias="isAccountOwner")
    display_name: Optional[StrictStr] = Field(default=None, alias="displayName")
    display_label: Optional[StrictStr] = Field(default=None, alias="displayLabel")
    opted_in_subscription_notifications: Optional[StrictBool] = Field(default=None, alias="optedInSubscriptionNotifications")
    opted_in_notifications: Optional[StrictBool] = Field(default=None, alias="optedInNotifications")
    avatar_src: Optional[StrictStr] = Field(default=None, alias="avatarSrc")
    login_count: Optional[StrictInt] = Field(default=None, alias="loginCount")
    created_from_url_id: Optional[StrictStr] = Field(default=None, alias="createdFromUrlId")
    sign_up_date: Optional[StrictInt] = Field(default=None, alias="signUpDate")
    email: Optional[StrictStr] = None
    website_url: Optional[StrictStr] = Field(default=None, alias="websiteUrl")
    username: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["groupIds", "hasBlockedUsers", "isProfileDMDisabled", "isProfileCommentsPrivate", "isProfileActivityPrivate", "isCommentModeratorAdmin", "isAdminAdmin", "isAccountOwner", "displayName", "displayLabel", "optedInSubscriptionNotifications", "optedInNotifications", "avatarSrc", "loginCount", "createdFromUrlId", "signUpDate", "email", "websiteUrl", "username", "id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAPISSOUserData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAPISSOUserData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "groupIds": obj.get("groupIds"),
            "hasBlockedUsers": obj.get("hasBlockedUsers"),
            "isProfileDMDisabled": obj.get("isProfileDMDisabled"),
            "isProfileCommentsPrivate": obj.get("isProfileCommentsPrivate"),
            "isProfileActivityPrivate": obj.get("isProfileActivityPrivate"),
            "isCommentModeratorAdmin": obj.get("isCommentModeratorAdmin"),
            "isAdminAdmin": obj.get("isAdminAdmin"),
            "isAccountOwner": obj.get("isAccountOwner"),
            "displayName": obj.get("displayName"),
            "displayLabel": obj.get("displayLabel"),
            "optedInSubscriptionNotifications": obj.get("optedInSubscriptionNotifications"),
            "optedInNotifications": obj.get("optedInNotifications"),
            "avatarSrc": obj.get("avatarSrc"),
            "loginCount": obj.get("loginCount"),
            "createdFromUrlId": obj.get("createdFromUrlId"),
            "signUpDate": obj.get("signUpDate"),
            "email": obj.get("email"),
            "websiteUrl": obj.get("websiteUrl"),
            "username": obj.get("username"),
            "id": obj.get("id")
        })
        return _obj


