# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from fastcomments_client.models.comment_user_badge_info import CommentUserBadgeInfo
from typing import Optional, Set
from typing_extensions import Self

class PublicComment(BaseModel):
    """
    PublicComment
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    var_date: datetime = Field(alias="date")
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    anon_user_id: Optional[StrictStr] = Field(default=None, alias="anonUserId")
    commenter_name: StrictStr = Field(alias="commenterName")
    commenter_link: Optional[StrictStr] = Field(default=None, alias="commenterLink")
    comment_html: StrictStr = Field(alias="commentHTML")
    parent_id: Optional[StrictStr] = Field(default=None, alias="parentId")
    votes: Optional[StrictInt] = None
    votes_up: Optional[StrictInt] = Field(default=None, alias="votesUp")
    votes_down: Optional[StrictInt] = Field(default=None, alias="votesDown")
    verified: StrictBool
    avatar_src: Optional[StrictStr] = Field(default=None, alias="avatarSrc")
    is_spam: Optional[StrictBool] = Field(default=None, alias="isSpam")
    has_images: Optional[StrictBool] = Field(default=None, alias="hasImages")
    is_deleted: Optional[StrictBool] = Field(default=None, alias="isDeleted")
    is_deleted_user: Optional[StrictBool] = Field(default=None, alias="isDeletedUser")
    is_by_admin: Optional[StrictBool] = Field(default=None, alias="isByAdmin")
    is_by_moderator: Optional[StrictBool] = Field(default=None, alias="isByModerator")
    is_pinned: Optional[StrictBool] = Field(default=None, alias="isPinned")
    is_locked: Optional[StrictBool] = Field(default=None, alias="isLocked")
    rating: Optional[Union[StrictFloat, StrictInt]] = None
    display_label: Optional[StrictStr] = Field(default=None, alias="displayLabel")
    badges: Optional[List[CommentUserBadgeInfo]] = None
    feedback_ids: Optional[List[StrictStr]] = Field(default=None, alias="feedbackIds")
    view_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="viewCount")
    requires_verification: Optional[StrictBool] = Field(default=None, alias="requiresVerification")
    edit_key: Optional[StrictStr] = Field(default=None, alias="editKey")
    is_unread: Optional[StrictBool] = Field(default=None, alias="isUnread")
    my_vote_id: Optional[StrictStr] = Field(default=None, alias="myVoteId")
    is_voted_down: Optional[StrictBool] = Field(default=None, alias="isVotedDown")
    is_voted_up: Optional[StrictBool] = Field(default=None, alias="isVotedUp")
    has_children: Optional[StrictBool] = Field(default=None, description="This is always set when asTree=true", alias="hasChildren")
    nested_children_count: Optional[StrictInt] = Field(default=None, description="The total nested child count included in this response (may be more available w/ pagination) Only set with asTree=true, otherwise this will be null.", alias="nestedChildrenCount")
    child_count: Optional[StrictInt] = Field(default=None, description="You must ask the API to count children (with asTree=true&countChildren=true), otherwise this will be null. This will be the complete direct child count, whereas children may only contain a subset based on pagination.", alias="childCount")
    children: Optional[List[PublicComment]] = None
    is_flagged: Optional[StrictBool] = Field(default=None, alias="isFlagged")
    is_blocked: Optional[StrictBool] = Field(default=None, alias="isBlocked")
    __properties: ClassVar[List[str]] = ["_id", "date", "userId", "anonUserId", "commenterName", "commenterLink", "commentHTML", "parentId", "votes", "votesUp", "votesDown", "verified", "avatarSrc", "isSpam", "hasImages", "isDeleted", "isDeletedUser", "isByAdmin", "isByModerator", "isPinned", "isLocked", "rating", "displayLabel", "badges", "feedbackIds", "viewCount", "requiresVerification", "editKey", "isUnread", "myVoteId", "isVotedDown", "isVotedUp", "hasChildren", "nestedChildrenCount", "childCount", "children", "isFlagged", "isBlocked"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicComment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in badges (list)
        _items = []
        if self.badges:
            for _item_badges in self.badges:
                if _item_badges:
                    _items.append(_item_badges.to_dict())
            _dict['badges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict['children'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicComment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "date": obj.get("date"),
            "userId": obj.get("userId"),
            "anonUserId": obj.get("anonUserId"),
            "commenterName": obj.get("commenterName"),
            "commenterLink": obj.get("commenterLink"),
            "commentHTML": obj.get("commentHTML"),
            "parentId": obj.get("parentId"),
            "votes": obj.get("votes"),
            "votesUp": obj.get("votesUp"),
            "votesDown": obj.get("votesDown"),
            "verified": obj.get("verified"),
            "avatarSrc": obj.get("avatarSrc"),
            "isSpam": obj.get("isSpam"),
            "hasImages": obj.get("hasImages"),
            "isDeleted": obj.get("isDeleted"),
            "isDeletedUser": obj.get("isDeletedUser"),
            "isByAdmin": obj.get("isByAdmin"),
            "isByModerator": obj.get("isByModerator"),
            "isPinned": obj.get("isPinned"),
            "isLocked": obj.get("isLocked"),
            "rating": obj.get("rating"),
            "displayLabel": obj.get("displayLabel"),
            "badges": [CommentUserBadgeInfo.from_dict(_item) for _item in obj["badges"]] if obj.get("badges") is not None else None,
            "feedbackIds": obj.get("feedbackIds"),
            "viewCount": obj.get("viewCount"),
            "requiresVerification": obj.get("requiresVerification"),
            "editKey": obj.get("editKey"),
            "isUnread": obj.get("isUnread"),
            "myVoteId": obj.get("myVoteId"),
            "isVotedDown": obj.get("isVotedDown"),
            "isVotedUp": obj.get("isVotedUp"),
            "hasChildren": obj.get("hasChildren"),
            "nestedChildrenCount": obj.get("nestedChildrenCount"),
            "childCount": obj.get("childCount"),
            "children": [PublicComment.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "isFlagged": obj.get("isFlagged"),
            "isBlocked": obj.get("isBlocked")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
PublicComment.model_rebuild(raise_errors=False)

