# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from fastcomments_client.models.imported_api_status_success import ImportedAPIStatusSUCCESS
from fastcomments_client.models.pick_f_comment_is_deleted_or_comment_htmlor_commenter_name_or_user_id import PickFCommentIsDeletedOrCommentHTMLOrCommenterNameOrUserId
from typing import Optional, Set
from typing_extensions import Self

class PublicAPIDeleteCommentResponse(BaseModel):
    """
    PublicAPIDeleteCommentResponse
    """ # noqa: E501
    comment: Optional[PickFCommentIsDeletedOrCommentHTMLOrCommenterNameOrUserId] = None
    hard_removed: StrictBool = Field(alias="hardRemoved")
    status: ImportedAPIStatusSUCCESS
    __properties: ClassVar[List[str]] = ["comment", "hardRemoved", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicAPIDeleteCommentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of comment
        if self.comment:
            _dict['comment'] = self.comment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicAPIDeleteCommentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment": PickFCommentIsDeletedOrCommentHTMLOrCommenterNameOrUserId.from_dict(obj["comment"]) if obj.get("comment") is not None else None,
            "hardRemoved": obj.get("hardRemoved"),
            "status": obj.get("status")
        })
        return _obj


