# coding: utf-8

"""
    fastcomments

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from fastcomments_client.models.notification_type import NotificationType
from typing import Optional, Set
from typing_extensions import Self

class RenderableUserNotification(BaseModel):
    """
    RenderableUserNotification
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    url_id: StrictStr = Field(alias="urlId")
    url: StrictStr
    page_title: Optional[StrictStr] = Field(default=None, alias="pageTitle")
    related_object_type: Union[StrictFloat, StrictInt] = Field(alias="relatedObjectType")
    related_object_id: StrictStr = Field(alias="relatedObjectId")
    viewed: StrictBool
    sent: StrictBool
    created_at: datetime = Field(alias="createdAt")
    type: NotificationType
    from_comment_id: Optional[StrictStr] = Field(default=None, alias="fromCommentId")
    from_user_name: StrictStr = Field(alias="fromUserName")
    from_user_id: StrictStr = Field(alias="fromUserId")
    from_user_avatar_src: Optional[StrictStr] = Field(default=None, alias="fromUserAvatarSrc")
    opted_out: StrictBool = Field(alias="optedOut")
    conversation_id: Optional[StrictStr] = Field(default=None, alias="conversationId")
    context_html: Optional[StrictStr] = Field(default=None, alias="contextHTML")
    __properties: ClassVar[List[str]] = ["_id", "urlId", "url", "pageTitle", "relatedObjectType", "relatedObjectId", "viewed", "sent", "createdAt", "type", "fromCommentId", "fromUserName", "fromUserId", "fromUserAvatarSrc", "optedOut", "conversationId", "contextHTML"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RenderableUserNotification from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RenderableUserNotification from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "urlId": obj.get("urlId"),
            "url": obj.get("url"),
            "pageTitle": obj.get("pageTitle"),
            "relatedObjectType": obj.get("relatedObjectType"),
            "relatedObjectId": obj.get("relatedObjectId"),
            "viewed": obj.get("viewed"),
            "sent": obj.get("sent"),
            "createdAt": obj.get("createdAt"),
            "type": obj.get("type"),
            "fromCommentId": obj.get("fromCommentId"),
            "fromUserName": obj.get("fromUserName"),
            "fromUserId": obj.get("fromUserId"),
            "fromUserAvatarSrc": obj.get("fromUserAvatarSrc"),
            "optedOut": obj.get("optedOut"),
            "conversationId": obj.get("conversationId"),
            "contextHTML": obj.get("contextHTML")
        })
        return _obj


